### ISSUE TITLE
Duplicate authority warning pops up in connection with $g

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#1003]
Many of our personal name authorities exist twice - one if the full authority record, the other one has the same 100 $a plus a $g with the name of the country. The same is true for corporate authorities - they have [modifiers](https://www.un.org/depts/dhl/unbisref_manual/bd/guidelines/g610.htm#2) in $g. These are two distinct authorities, they should not be considered duplicates. However, we get the duplicate authority warning pop up in these cases - can we change that? The check for duplicates should include 1XX $a and $g. 

https://user-images.githubusercontent.com/110108422/221975459-04e11028-a51c-4901-9d2b-b40e9fe39f80.mp4

Here are two corporate names that cannot be modified and saved because they are considered duplicates:

![image](https://user-images.githubusercontent.com/110108422/230963091-97a5ce0a-e1d7-41b2-89c4-1c7d012ee046.png)

**Comment by susanhussein** [comment]
https://user-images.githubusercontent.com/125896362/221984095-8e2a6713-3ed6-4b32-8e7c-e83046d4d3e7.mp4

Another example of this

**Comment by viola-v** [comment]
Reopening this issue since it hasn't been fixed as far as I can tell. Here's a video:

https://user-images.githubusercontent.com/110108422/234382659-a1c67cfb-ebf1-4ddb-be4c-b4d7c51a2b4a.mp4
