### ISSUE TITLE
Copy/paste using check boxes does not copy all fields

### ISSUE THREAD

**Issue by ashley-laura** [dag-hammarskjold-library/dlx-rest#1011]
Possibly related to #990 but not the same issue. 
When you select several fields with the check boxes and try to copy them over to a different record, not all of them get copied over. In the video example, 650:SWEDEN does not get copy/pasted. I mostly have noticed the issue with 650s specifically.

https://user-images.githubusercontent.com/118854556/222250914-3328c649-fa8f-4c3c-bc0d-5e30077bcf40.mp4

**Comment by aaronhelton** [comment]
So far I haven't been able to reproduce this issue at all. I can see it in the video, but I can't reproduce it.

**Comment by ashley-laura** [comment]
exactly the problem, it keeps happening but totally at random and we can't find a pattern! :(

**Comment by aaronhelton** [comment]
Note: try this on a larger selection of fields.
