### ISSUE TITLE
Remove vote and speech records from the bib tab (search and browse)

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#1014]
We want to completely separate these collections - related to #1006 and #785 . 

```[tasklist]
### Tasks
```

**Comment by viola-v** [comment]
Just adding some notes and thoughts on issues we're trying to resolve:

Currently, when I look for a meeting record, I also get all the speech records - depending on the sort, it might show up at the top or somewhere at the bottom:

![image](https://github.com/dag-hammarskjold-library/dlx-rest/assets/110108422/fd2d75ae-365a-45e0-a88a-dcf419ea7491)

When I browse by a meeting record symbol, I cannot get directly to the meeting record or add it to the basket, because the count includes the speech records as well:

![image](https://github.com/dag-hammarskjold-library/dlx-rest/assets/110108422/df3a5108-441d-4cd6-8786-ca64da02920a)

Same issue with the resolutions and voting records:

![image](https://github.com/dag-hammarskjold-library/dlx-rest/assets/110108422/42ba5dd0-e153-45a6-ba95-5e633ad949a8)

For the search, a solution might be to include filters based on 989 $a, similar to what we have in the authorities:

![image](https://github.com/dag-hammarskjold-library/dlx-rest/assets/110108422/a9301167-e678-440f-a3b1-656f716af6c8)

Instead of 100, 110, etc. we could have "Documents and Publications", "Speeches" and "Votes".

I'm still thinking that it might be nice to have a separate tab for "Docs", so that I can go there if I know that I don't want to look at anything other than documents and publications.

And we might need that anyway in the Browse section to ensure that we can browse for all bibs, but also separately for documents and publications to make sure that we only have one result per symbol (and not more if meeting records or resolutions are involved).

And we definitely want to resolve the related issue in #785  - having the search criteria included in the search box is annoying:

![image](https://github.com/dag-hammarskjold-library/dlx-rest/assets/110108422/b1286bc0-5df8-4374-9534-27b3457bb926)

**Comment by meropeee** [comment]
New mock-up: https://www.figma.com/proto/xmMyAnPg8YzjAkiWnh6ASM/Marc-Editor?node-id=4009-25572&t=VradI0Y208A5APLh-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A2&hide-ui=1
