### ISSUE TITLE
Auth record not showing in browse by auth/author results

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#1018]
Susan H. just reported this - the 100 authority  "Mack, Jason" shows up in in browse by auth/subject, but not in auth/author. It's an existing authority that hasn't been modified recently:

![image](https://user-images.githubusercontent.com/110108422/223136378-e010d1cd-012e-48af-9d60-85b973bbbeeb.png)

![image](https://user-images.githubusercontent.com/110108422/223136667-bfda9e9c-fe82-42eb-8730-e1dfc862a59a.png)

And just taking the screenshot I noticed that "Mack, Mr." is missing from the auth/author results as well - that is a very recent authority, but it should still show up:

![image](https://user-images.githubusercontent.com/110108422/223136786-9e7b521d-770e-478a-bfc7-70675e1eb8b4.png)

We have existing issues #986 and #903 which might be related.

**Comment by aaronhelton** [comment]
Closed by #1028

**Comment by viola-v** [comment]
Reopening this issue since we just discovered the following:

This authority shows up when browsing auth/subject at Ostoni, Federica:

![image](https://user-images.githubusercontent.com/110108422/235752466-54ec1a1e-4f09-45d6-b0b3-7a01c7d80061.png)

But it doesn't show up when browsing auth/author:

![image](https://user-images.githubusercontent.com/110108422/235752685-6c7d975a-1692-4d41-9fcf-e1b327a9ef4f.png)

This is the authority record:
![image](https://user-images.githubusercontent.com/110108422/235752857-83e5fc6f-10d9-45e7-afd2-d514aef6d04f.png)

**Comment by jbukhari** [comment]
The auth is only being used in speech records at the moment. So it's not in the bib browse list, but it is in speech

![image](https://user-images.githubusercontent.com/5749758/235964854-61285f4c-0b6b-426e-9d2d-118fc3a73d0d.png)

**Comment by viola-v** [comment]
@jbukhari I wasn't looking at bib browsing, just auth browsing. It should show up in auth browsing by both author and subject, right? It's a 100 authority record, so it should be in both the author and subject indexes for authority browsing?

**Comment by viola-v** [comment]
Just adding another example flagged by Susan H.: 
![image](https://github.com/dag-hammarskjold-library/dlx-rest/assets/110108422/e6375611-c61c-4b7e-ab34-df24f7722ad4)

**Comment by viola-v** [comment]
Check if it solves this issue once deployed to production (it looks ok in QAT, but I'm not sure if the data is up-to-date enough to be sure):

This authority doesn't show up in browse results:
![image](https://github.com/dag-hammarskjold-library/dlx-rest/assets/110108422/b5be2009-9d9f-4fa5-ba7c-c3d2c0e41b2f)

![image](https://github.com/dag-hammarskjold-library/dlx-rest/assets/110108422/ab33f056-c8ce-4e5b-a3dd-7f9672b74566)
