### ISSUE TITLE
Voting records not showing in browse by vote/symbol results

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#1020]
![image](https://user-images.githubusercontent.com/110108422/223440628-5540bdfd-a661-4d2a-a299-cfb707242b3e.png)

These three voting records missing from the results above:

![image](https://user-images.githubusercontent.com/110108422/223440832-d3ea901b-428c-4c72-a79a-a92cf5a55ec5.png)

**Comment by viola-v** [comment]
Just to add that I added a new voting record just now and that is showing up right away in the browse index: 
![image](https://user-images.githubusercontent.com/110108422/223441700-8fd8175f-920b-48a8-8db4-207d33d6b807.png)

But the other three are still missing.

**Comment by aaronhelton** [comment]
This might also be addressed by #1028
