### ISSUE TITLE
Thesaurus records in ME don't have latest updates from Horizon

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#1021]
This Horizon record has a 682 field and an update in 2021, but the field is [missing in the ME and the last update is from 2020](https://metadata.un.org/editor/records/auths/search?q=id%3A269926&start=1&limit=25&sort=updated&direction=desc&search=&format=brief)

![image](https://user-images.githubusercontent.com/110108422/224430551-1c5c8f4d-bd36-432d-b9ca-73bbf73a9746.png)

![image](https://user-images.githubusercontent.com/110108422/224430616-874f5447-4f96-4f7f-92a1-9b32bc570349.png)

**Comment by aaronhelton** [comment]
Thesaurus terms were excluded from authority updates, so this is expected.

682 is the field we agreed to use for deprecation/replacement, which is something that happens in Vocbench, where the thesaurus terms are maintained. See also #190
