### ISSUE TITLE
How does spell-check work? What does it cover?

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#1022]
Mayumi just pointed out that it didn't catch this typo (Genera's instead of General's): 
![image](https://user-images.githubusercontent.com/110108422/224774731-7b29bb2f-9f71-41fd-a638-a30b3ab46b02.png)

**Comment by aaronhelton** [comment]
Spell check is handled at the browser level. We don't implement one in the app.

**Comment by viola-v** [comment]
Just to confirm - that means we have no control over it? It's what comes out of the box with each browser?

**Comment by aaronhelton** [comment]
Correct. There are spell check libraries out there, but we're deferring to what individual users have in their browsers for this.
