### ISSUE TITLE
Agenda items not found in browse but in search

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#1030]
Griet flagged the following issue:

When you do a browse by speach/agenda for E/L.1282 2, you get a result with zero records attached:

![image](https://user-images.githubusercontent.com/110108422/226721654-23024e58-149e-4425-bb2f-e24ac61658bc.png)

However, when you [search for it in the authorities](https://metadata.un.org/editor/records/auths/search?q=agenda%3AE%2FL.1282*&start=1&limit=25&sort=updated&direction=desc&search=symbol%3AE%2FL.1282*&format=brief), you find the record with 12 bibs attached:
![image](https://user-images.githubusercontent.com/110108422/226721941-11d2b8d8-752f-4e28-805f-db85d89cfde4.png)

Here's another example: 
![image](https://user-images.githubusercontent.com/110108422/226722867-49bb5961-968b-4291-bb1f-fe1f35c9ffba.png)
![image](https://user-images.githubusercontent.com/110108422/226722928-65ec6db1-0aae-42c4-9b06-0131070499a9.png)

The apostrophe is a common denominator - could that cause an issue?

**Comment by jbukhari** [comment]
This is most likely due to the auth attached records update issue

**Comment by viola-v** [comment]
The first example from above works in QAT:

![image](https://user-images.githubusercontent.com/110108422/227605080-bbae6796-a65c-49bc-b050-9eff8c725221.png)

The second one doesn't:

![image](https://user-images.githubusercontent.com/110108422/227605429-e37b03a4-b1fb-4693-80ed-92b433832015.png)

Not sure what that means...

**Comment by viola-v** [comment]
A few more examples in QAT that don't work (all with apostrophes):

![image](https://user-images.githubusercontent.com/110108422/227606725-98290de0-b896-4390-9cd5-6cca64fe20b0.png)

![image](https://user-images.githubusercontent.com/110108422/227607002-0dca514c-ebe2-4f5b-aa49-c8e2d2245e25.png)

![image](https://user-images.githubusercontent.com/110108422/227607388-b51b6bda-64e3-4b13-9a18-b4be70583a03.png)

![image](https://user-images.githubusercontent.com/110108422/227607477-2aee65b7-9336-4719-86bd-f6d36b6e69a4.png)

The search works when I take out the part with the apostrophe:

![image](https://user-images.githubusercontent.com/110108422/227607621-6e0595e6-8bd5-465a-89cc-e613bad6a1d7.png)

**Comment by viola-v** [comment]
This seems to work properly now.
