### ISSUE TITLE
Validations for 100/700 $g

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#1058]
For speech records, we frequently create new authorities from the bib with 700 $g, which contains a country name and should always start and end with parentheses:
![image](https://user-images.githubusercontent.com/110108422/234621427-e0f0858f-8c55-426a-b8d7-6300f4dedf06.png)

When revising these records, if the parentheses are missing, we have to edit the authority record, which is an additional step. So ideally we wouldn't be able to save a new authority from the bib when the parantheses in 700 $g are missing, like in this example: 
![image](https://user-images.githubusercontent.com/110108422/234620791-1c6331dd-1aaf-4e33-9738-240ca86b55a0.png)

Not sure if this validation would be at the 100 or 700 field...

**Comment by aaronhelton** [comment]
This validation would use a regex on the 100$g (authority record)

**Comment by viola-v** [comment]
I just tested this in QAT and it let me create a new authority record without parantheses: 
![image](https://github.com/dag-hammarskjold-library/dlx-rest/assets/110108422/e555fd59-1277-4d2e-a701-5695df4c116c)

**Comment by aaronhelton** [comment]
I see that the validation is applied on auth 100$g, but should it also be applied on 700$g? @jbukhari

**Comment by aaronhelton** [comment]
@viola-v did we decide this was okay as-is and the fix for it will be in #1071 ? If so, can we close this issue?

**Comment by viola-v** [comment]
Yes!
