### ISSUE TITLE
Duplicate authority warning pops up in connection with $9

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#1063]
Probably related to #1003 

I want to delete $9 in the record on the left (it's the same problem in QAT and production):

![image](https://user-images.githubusercontent.com/110108422/235935459-be2e49c8-fc9e-4018-8d94-0d91c998b26a.png)

But when I try to the save the record, I get this error message:

![image](https://user-images.githubusercontent.com/110108422/235935618-2bde3e0f-60e2-40e8-bb0c-a1d593505aa7.png)

@jbukhari Does your fix in #1059 take this into consideration?

**Comment by jbukhari** [comment]
@viola-v yes this should have been have been resolved with #1059
