### ISSUE TITLE
Basket Batch Update

### ISSUE THREAD

**Issue by meropeee** [dag-hammarskjold-library/dlx-rest#1065]
As discussed here: [https://unitednations.sharepoint.com/sites/MarcEditorProject/_layouts/15/Doc.aspx?sourcedoc={8edfffcf-8684-429c-a49c-33788255cdcb}&action=edit&wd=target%28General.one%7C46b5c076-e444-4045-8ab5-41368ac3d971%2FEnhancements%7Cbe4cd68f-789c-4797-8c71-c28f23038172%2F%29&wdorigin=NavigationUrl](url)

Prototype here: [https://www.figma.com/proto/xmMyAnPg8YzjAkiWnh6ASM/Marc-Editor?type=design&node-id=1332-4315&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A2](url)

**Comment by JoelleSciboz** [comment]
Envisioned as a solution to #1015 and #655

**Comment by aaronhelton** [comment]
Q: For delete, do we delete the field from all selected records where the field, subfields, and values match the selected field; OR do we delete all instances of the field tag from all selected records?

**Comment by meropeee** [comment]
What would be the expected behavior if the user would like to delete a selected field from a record?  If field is selected for deletion, all the respective matching field codes from all the items of the basket will be deleted, regardless of their value/ subfields.

**Comment by meropeee** [comment]
What would be the expected behavior if the user would like to delete a selected field from a record?  If field is selected for deletion, all the respective matching field codes from all the items of the basket will be deleted, regardless of their value/ subfields.
