### ISSUE TITLE
Speech record validation - 710 and 711

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#1072]
From Valeria: Currently, 710 is a required field for speech records, but either 710 or 711 should be required. If that's not possible right now, neither one should be required for the time being, so that we can save a record with just a 711 but no 710 field, and this change needs to be made asap.

**Comment by aaronhelton** [comment]
Make 710 not required in speech records for the time being.

Future: Can we make two fields either/or required?
