### ISSUE TITLE
Speech review section

### ISSUE THREAD

**Issue by JoelleSciboz** [dag-hammarskjold-library/dlx-rest#1078]
The following fields should be displayed in columns, and columns should be sortable, which will allow the reviser to apply primary, secondary, etc. sorting.

- Meeting records symbol (791)
- Speaker (700)
- Country organization (710 and 711)
- Meeting date (992)

In addition, agenda information (991 a b c and d) should be displayed but not sortable since the field might be repeated. 
From the screen, the reviser should be able to add records in their basket as it is possible in other sections.

**Comment by viola-v** [comment]
Next steps discussed on 28 July: Meropi will meet with Valeria to create mock-ups

**Comment by viola-v** [comment]
Meropi met with Valeria and will create mock-ups.

**Comment by JoelleSciboz** [comment]
@meropeee We have an additional requirements for the mock-up:
- If the record has multiple agendas, each should be displayed in a different line.

**Comment by meropeee** [comment]
Hello Joelle, Could you please provide an example with of a record that has multiple agendas?

**Comment by JoelleSciboz** [comment]
Here are a couple of examples with multiple 991.

Gamba, Virginia (UN. Special Representative of the Secretary-General for Children and Armed Conflict)
S/PV.9258 | 2023-02-13 | Speeches
S/78 [187] – CHILDREN IN ARMED CONFLICTS
S/78 [59] – UKRAINE—POLITICAL CONDITIONS
https://metadata.un.org/editor/editor?records=bibs/1368111

Ramaphosa, Matamela Cyril (South Africa. President)
A/76/PV.5 | 2021-09-22 | Speeches
A/76/251 72b – Comprehensive implementation of and follow-up to the Durban Declaration and Programme of Action. @920450 |$d RACIAL DISCRIMINATION--PROGRAMME IMPLEMENTATION
A/76/251 [904] – UN. GENERAL ASSEMBLY (76TH SESS. : 2021-2022)--SPECIAL STATEMENTS
https://metadata.un.org/editor/editor?records=bibs/1321801

!The following one has 14 agenda. 
https://metadata.un.org/editor/editor?records=bibs/518426
Ellemann-Jensen, U. (Denmark) (European Communities)
A/42/PV.6 | 1987-09-22 | Speeches

**Comment by wernerval** [comment]
As discussed in the latest meeting, 991 field will not be included

**Comment by wernerval** [comment]
If possible, I would like to add as a column/sorting field 700 $g
Thank you
