### ISSUE TITLE
Use _record_type logical field to distinguish between record types

### ISSUE THREAD

**Issue by jbukhari** [dag-hammarskjold-library/dlx-rest#1093]
Currently, the criteria for determining what record type to search (vote, speech, etc) is hardcoded in the search route. The _record_type logical field is determined by criteria set in the configurations, which is a preferable place to record the criteria. The browse functionality is already using this field.

**Comment by aaronhelton** [comment]
@jbukhari Is this fixed now by #1388 or is there something else to do?
