### ISSUE TITLE
File Upload: UI in Manage Files trims space 

### ISSUE THREAD

**Issue by meropeee** [dag-hammarskjold-library/dlx-rest#1109]
Item Description: UI in Manage Files trims space at the end of the symbol and it doesn’t show it so as we delete it. If we add it manually it shows. This happens only on the files where _replaced with space from gdoc-dlx.
{"identifiers.0.value" : " A_77_730 "}

Proposed Solution: Keep and Show the space in the UI and don’t trim it so we can correct it

Comments:None

**Comment by Yalshire2004** [comment]
fixed
