### ISSUE TITLE
Multiple uppercase ANDs in an authority heading throws an exception when saving

### ISSUE THREAD

**Issue by aaronhelton** [dag-hammarskjold-library/dlx-rest#1118]
This seems to be Atlas related.

Authority headings that contain multiple uppercase AND strings throw a pymongo exception:

`pymongo.errors.OperationFailure: Too many text expressions, full error: {'ok': 0.0, 'errmsg': 'Too many text expressions', 'code': 2, 'codeName': 'BadValue', '$clusterTime': {'clusterTime': Timestamp(1685105324, 4), 'signature': {'hash': b'\x9e*b\xa1\xdc0\xcb^\xc7&\x1c\xfd 4UDs\xd4\xaf\xf0', 'keyId': 7226800079208710149}}, 'operationTime': Timestamp(1685105324, 4)}`

This is specifically related to the count_documents() function.

To reproduce this: 
1. Using the dev database and running on localhost, navigate to /editor/editor?records=auths/370019
2. Change the heading, 110$a, to something that contains multiple AND strings, e.g., FOOD AND PEACE AND SECURITY
3. Attempt to save, noting the error thrown in the terminal.
4. Note that using lower case "and" does not cause the issue, nor does the case of the rest of the heading text matter.

**Comment by aaronhelton** [comment]
@jbukhari  if we can't get to this within a week, I will move it to 2.0.8.

**Comment by jbukhari** [comment]
The issue with any uppercase instances of "AND" in any text search, not just in authorities and it doesn't have to be multiple. It also applies to "OR". The issue is differentiating the use of "AND" and "OR" operators as conjunctions between fields, and using them as part of text searches

**Comment by viola-v** [comment]
Just throwing in a screenshot of what the error looks like on the user-side: 

![image](https://github.com/dag-hammarskjold-library/dlx-rest/assets/110108422/e79d604f-147d-4dcd-8ace-b45e36e917cb)

**Comment by aaronhelton** [comment]
@jbukhari I don't know where you are with this issue, but I was playing around with dlx.marc.query.from_string.tokenize L#25 and found that if you add "/" to the character checking, it prevents this error. That seems to be because the authHeadingInUse function from jmarc.mjs wraps the value it's sending to the search API in a regex, so we can use "/" to indicate that the string is "in quotes". I don't know if there are any unintended consequences of this, however.

If not, here's what I'm suggesting:

```
for i, char in enumerate(string):
    if char in ['"', "'", "/"]:
        # toggle
        in_quotes = not in_quotes
```
