### ISSUE TITLE
Logical field country_org needs to include 711

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#1152]
Griet flagged this:

The following search doesn't bring back any results: 

https://metadata.un.org/editor//records/bibs/search?q=country_org%3A%27UN+Conference+on+the+Human+Environment+(1972+%3A+Stockholm).+Secretariat.+Director%27+AND+089%3A%27B22%27

But it does when I change country_org to 711:

https://metadata.un.org/editor/records/bibs/search?q=711%3A%27UN+Conference+on+the+Human+Environment+%281972+%3A+Stockholm%29.+Secretariat.+Director%27+AND+089%3A%27B22%27&start=1&limit=25&sort=updated&direction=desc&search=%3A711%27UN+Conference+on+the+Human+Environment+%281972+%3A+Stockholm%29.+Secretariat.+Director%27+AND+089%3A%27B22%27&format=brief

I checked the [list of logical fields](https://unitednations.sharepoint.com/:x:/s/MarcEditorProject/EbYl3NGw5GlPvGrq0YjzvdkBU1zBUNoHOwwiXIDdkbsETw?e=bwHfhL&wdLOR=c0240473C-00E6-4665-BA9B-1BACABAF8083), and it does look like I didn't list 711 as a field to be included in country_org, but it needs to be there. It would be great if this could be included in the next release!

**Comment by aaronhelton** [comment]
See: https://github.com/dag-hammarskjold-library/dlx/issues/243
