### ISSUE TITLE
Basket Batch Update - preview function

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#1169]
We discussed that we might like a preview function after all to see how the changes would affect the bib records (similar to the UNDL).

![image](https://github.com/dag-hammarskjold-library/dlx-rest/assets/110108422/a8274fea-ed4b-43d3-aece-957e7c2bcad4)

**Comment by meropeee** [comment]
Mockup Screen 1:

![image](https://github.com/dag-hammarskjold-library/dlx-rest/assets/118828817/93c889bb-0ac2-4ed1-9463-6c834dfa35fc)

Mockup Screen 2:

![image](https://github.com/dag-hammarskjold-library/dlx-rest/assets/118828817/b27a8f85-8e83-423f-8770-0b0c65ff563f)
