### ISSUE TITLE
Basket Batch Update - improve validation error messaging

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#1172]
Currently doesn't tell you which fields/subfields are the problem... We also aren't sure if update happens when there is a validation error. Messaging needs to be clearer.

**Comment by meropeee** [comment]
Updated user story:
I would like to be able to understand if in case of a validation error, whether the change will be committed or not. For records coming from Horizon in case of a validation error, the changes will be saved. For new records, in case of a validation error the changes will not be saved.
