### ISSUE TITLE
Display and sorting in browse indexes by subfield when not in order

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#1183]
It looks like the sorting in the browse indexes is not by the alphabetical order of the subfields in the record, but rather by the order in which they display in the field? Here is an example:

![image](https://github.com/dag-hammarskjold-library/dlx-rest/assets/110108422/a897c3ca-b69a-4c97-af22-bd06e5eda7e6)

This is what the second record in the list looks like - the subfields in 191 are not in order, but the index seems to read them as they are in the record and thus puts it in the wrong place in the browse index:

![image](https://github.com/dag-hammarskjold-library/dlx-rest/assets/110108422/df3cd60b-a171-4a4c-86c9-89582bc68f8b)

It should appear here: 
![image](https://github.com/dag-hammarskjold-library/dlx-rest/assets/110108422/5dc2a8a1-5f90-40ef-b0e6-d2b857da57ff)

**Comment by jbukhari** [comment]
The logical field values are currently recorded in the order the subfields are found in the record. 

Possible changes: 
* re-order all subfields into alphabetical order on record save
* force the logical field to build its value from the subfields in alphabetical order

**Comment by viola-v** [comment]
Re-ordering all subfields into alphabetical order on record save is what we had initially, but that doesn't work because in some cases the order as entered has semantic value that needs to be maintained (505 for example):

![image](https://github.com/dag-hammarskjold-library/dlx-rest/assets/110108422/92684663-172e-4772-9af4-53eaa6b26094)


So I'm afraid we have to go with the second solution you proposed - force the logical field to build its value from the subfields in alphabetical order (which I assume is more work)...
