### ISSUE TITLE
Tag doesn't change in bib records when updated in authority

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#1262]
When you change the type of an authority record, for example from 110 to 100, the bib record doesn't get updated accordingly. Susan H. noticed this when she made this update and then tried to merge the authority records and it didn't work. The merge did work once I modified the corresponding 710 in the bib record to a 700.

Examples:
auths/820497
auths/937261 => created by mistake as 110, was then changed to 100
bibs/1383351 and bibs/1383350 still show 710 instead of 700

**Comment by aaronhelton** [comment]
Suggestion: Revisit this issue when the global batch update is in place.

**Comment by viola-v** [comment]
Adding screenshots to the records before I fixed them: 
![image](https://github.com/dag-hammarskjold-library/dlx-rest/assets/110108422/31e06b40-f6b7-4a60-b16f-0fa4c60188c9)
![image](https://github.com/dag-hammarskjold-library/dlx-rest/assets/110108422/04e4730e-ddd6-4f6f-aeb9-04ce6f2b8207)

**Comment by viola-v** [comment]
> Suggestion: Revisit this issue when the global batch update is in place.

This issue came up again, and I just wanted to bump this in case the batch update changes anything. Also, it would be good to get a report of instances where we have a discrepancy between the type of heading in the bib and the auth...

**Comment by JoelleSciboz** [comment]
I had the opposite issue. In the bib a 710 linking to a 150 authority. This should not be possible:

![image](https://github.com/user-attachments/assets/a25bbd78-cc43-44ce-b0dc-34c1d32db807)

This 710 was linking to auth no. 273375

**Comment by aaronhelton** [comment]
It looks like the tag itself was changed without re-performing the lookup.
