### ISSUE TITLE
Issues with speech browse results in UAT

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#1266]
Valeria pointed out that the speech browse results in UAT differ from production even for older records, for example: 

![image](https://github.com/dag-hammarskjold-library/dlx-rest/assets/110108422/a8b49066-f917-4ea5-a5fa-a6f385ab6364)

The records were created years ago, so they should all be in UAT as well. I haven't checked QAT, it won't open in the office for me.

**Comment by viola-v** [comment]
Ashley checked in QAT, and it's the same issue: 
![image](https://github.com/dag-hammarskjold-library/dlx-rest/assets/110108422/3fc2470e-b15f-4528-8898-d2602362ff2a)

@aaronhelton Is there a way to make sure that none of the other fixes in the release caused this or to confirm that this is indeed an index issue? I wouldn't want this to happen in production when we upgrade with the new release...

**Comment by aaronhelton** [comment]
This might be working now after recent updates.
