### ISSUE TITLE
Text and regex search in authority controlled subfields does not properly differentiate subfields

### ISSUE THREAD

**Issue by jbukhari** [dag-hammarskjold-library/dlx-rest#1276]
~i.e. `650__a:human rights` is returning the same results as `650__b:human rights`~

This applies only to subfields that exist within the field. i.e. 700$a and 700$g. For example, `700__a:smith` is returning the same results as `700__g:smith`

**Comment by aaronhelton** [comment]
This might have implications for the global batch update.

**Comment by viola-v** [comment]
Adding another example that came up: https://metadata.un.org/editor/records/bibs/search?q=089%3A%27B22%27+AND+700__a%3A%2F.*%5C%29%24%2F&start=1&limit=25&sort=updated&direction=desc&search=089%3A%27B22%27+AND+7001_a%3A%2F.*%5C%29%24%2F&format=brief

**Comment by jbukhari** [comment]
Should be closed by https://github.com/dag-hammarskjold-library/dlx/pull/280
