### ISSUE TITLE
Move link to Speech Review section

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#1306]
The current position for the link is a bit awkward - it is fine for now, but eventually we want to have it in a place that is more prominent/easier to access.
![image](https://github.com/dag-hammarskjold-library/dlx-rest/assets/110108422/05cac987-ee6b-4481-b4d0-2260e4aa0038)

**Comment by aaronhelton** [comment]
Maybe up top?
<img width="960" alt="Screenshot 2024-06-20 at 2 24 05 PM" src="https://github.com/dag-hammarskjold-library/dlx-rest/assets/617997/3363d0be-e9e9-45e6-85ea-3863cea53d9c">

**Comment by aaronhelton** [comment]
@JoelleSciboz @viola-v @wernerval See proposal above

**Comment by viola-v** [comment]
> Maybe up top? <img alt="Screenshot 2024-06-20 at 2 24 05 PM" width="960" src="https://private-user-images.githubusercontent.com/617997/341522517-3363d0be-e9e9-45e6-85ea-3863cea53d9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MzA2NDgsIm5iZiI6MTcxOTQzMDM0OCwicGF0aCI6Ii82MTc5OTcvMzQxNTIyNTE3LTMzNjNkMGJlLWU5ZTktNDVlNi04NWVhLTM4NjNjZWE1M2Q5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQxOTMyMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOWIyMDM3YmMwODBiNzljZjg4NmU1MjYzNTEyMDhjOWU1ZDNiMjA5YTgzZTA5MDQ5MTkyZDllMzE3YTFiNjRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rLnqXO4WTXiE0NyzKaTsEBgJxtwAPT2EdYWvBdQcDsU">

Valeria approved the mockup above (placement after Advanced Search)!
