### ISSUE TITLE
Fields to copy remain in memory after a batch add action

### ISSUE THREAD

**Issue by JoelleSciboz** [dag-hammarskjold-library/dlx-rest#1327]
When we perform a batch action, the fields that were added remained checked on the record from which the batch aciton was performed. 

- **Even when fields are unchecked manually - which is cumbersome - they remain in memory and are added to the next copy action.**
- **Even when the record is removed from the basket and the basket refreshed  - they remain in memory and are added to the next copy action**

To reproduce the issue:
- Add some fields in batch using the basket batch edit function.
- Close the record from which you have batch copied fields and remove it from the basket.
- Open a new record and try to add fields from this record only to one record.
- Perform the past using ctrl + P. it copied not only the fields selected from the second record, but also the fields I had already created from the batch edit in basket action.
- Same issue if you uncheck the fields manually.

It is important, because it creates risks to add fields by mistake.

**Comment by viola-v** [comment]
Adding a video: 

https://github.com/dag-hammarskjold-library/dlx-rest/assets/110108422/79e4cc59-1676-4b97-b842-8336badde1bd
