### ISSUE TITLE
NOT xref searches not working

### ISSUE THREAD

**Issue by jbukhari** [dag-hammarskjold-library/dlx-rest#1346]
The `NOT` is not being recognized by the search with xref searches, i.e. `NOT xref:273032`

**Comment by viola-v** [comment]
Just bumping this one up, if it's not too time-consuming to fix, it would be good to get this done sooner rather than later - we need this to work to clean up deprecated authorities.

**Comment by jbukhari** [comment]
Pending next dlx release https://github.com/dag-hammarskjold-library/dlx/pull/310
