### ISSUE TITLE
Cannot save authorities with " and /

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#1357]
Valeria flagged that she wasn't able to save changes to this authority record:

![image](https://github.com/dag-hammarskjold-library/dlx-rest/assets/110108422/4903df7a-d2b1-4c7e-a962-4a4e85792704)

I was able to save it after removing the quotation marks:

![image](https://github.com/dag-hammarskjold-library/dlx-rest/assets/110108422/b19764e8-d0ff-4de3-aa6d-d71da349af2b)

Quotation marks alone are not the issue though, I tested that in other records. It seems like the combination of quotation marks and a slash might be what's causing this?

**Comment by jbukhari** [comment]
Closed by dlx-rest PR https://github.com/dag-hammarskjold-library/dlx-rest/pull/1371
