### ISSUE TITLE
Links from browse results don't work

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#1405]
For example:

![image](https://github.com/dag-hammarskjold-library/dlx-rest/assets/110108422/61311b67-6bf2-48b4-97ed-dbee860876b9)

![image](https://github.com/dag-hammarskjold-library/dlx-rest/assets/110108422/ceac95d9-4754-4374-9798-4b5954f94718)

**Comment by aaronhelton** [comment]
Fixed by #1388

**Comment by aaronhelton** [comment]
![image](https://github.com/dag-hammarskjold-library/dlx-rest/assets/617997/509271ce-0c73-4578-910a-fe3738316e0a)
