### ISSUE TITLE
Search by symbol issues in UAT

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#1417]
I'm searching for S/PV.9110 in Bibs:
![image](https://github.com/dag-hammarskjold-library/dlx-rest/assets/110108422/64b9e2d2-2ea8-4ed7-9a5d-3aef2291d72a)

And I get this error message:
![image](https://github.com/dag-hammarskjold-library/dlx-rest/assets/110108422/d43871bc-8344-4841-8696-06518ee4bd0e)

Browsing doesn't find it either:
![image](https://github.com/dag-hammarskjold-library/dlx-rest/assets/110108422/30b3ca08-185d-461a-8ead-bc69dd0d8277)

It does work when I do an exact search:
![image](https://github.com/dag-hammarskjold-library/dlx-rest/assets/110108422/030da2b8-585e-4e1a-9c33-7992deb1d7e6)

**Comment by jbukhari** [comment]
The root of this issue is https://github.com/dag-hammarskjold-library/dlx-rest/issues/1428. 

#1421 allows the symbol search shortcut to work as a text search instead of a wildcard search, but note that wildcard search is still broken
