### ISSUE TITLE
File uploads over 30 MB cause server error

### ISSUE THREAD

**Issue by aaronhelton** [dag-hammarskjold-library/dlx-rest#1422]
The stack trace indicates an SSL issue, and we have a fix incoming for setting ssl = True for the production config, but this seems like something else. Testing on UAT, I get a 413: Request Entity Too Large error message.

**Comment by jbukhari** [comment]
@aaronhelton was this fixed by clearing hard disk pace on the server?

**Comment by aaronhelton** [comment]
Yes, it's fixed now, will close.
