### ISSUE TITLE
Related auth should lead to a new page containing All bibs - check #1014 mockup

### ISSUE THREAD

**Issue by meropeee** [dag-hammarskjold-library/dlx-rest#1424]
Environment UAT
Related to #1014: https://github.com/dag-hammarskjold-library/dlx-rest/issues/1014#issuecomment-1731835557

1. Open speech record:659019
2.  take 1 auth, ie: HIV/AIDS--REVIEW
3. Open auth: xref:607552
4. check number(224)
5. Open 224
6. 16 bibs appear - not all All 224 docs+speeches+votes appear

**Comment by aaronhelton** [comment]
- [ ] Use the 'all' record subtype parameter to get all of the records 
- [ ] Make that 'all' option available in the user interface

**Comment by aaronhelton** [comment]
Should be fixed
