### ISSUE TITLE
Different naming of basket item and in the editor’s menu. 

### ISSUE THREAD

**Issue by meropeee** [dag-hammarskjold-library/dlx-rest#1425]
Environment UAT
1. Different naming of basket item and in the editor’s menu (also in Prod). 

![image](https://github.com/dag-hammarskjold-library/dlx-rest/assets/118828817/9e1605b3-df67-4e1b-9680-3fa4642ee757)

**Comment by aaronhelton** [comment]
Closing this as done since the "Fixes" directive didn't do it.
