### ISSUE TITLE
Browse issues in UAT

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#1436]
I'm browsing for S/PV.9110 in Bibs:

![image](https://github.com/dag-hammarskjold-library/dlx-rest/assets/110108422/da7f2f47-9365-4ea9-a8a8-c621200c51e3)

It does work when I do an exact search:

![image](https://github.com/dag-hammarskjold-library/dlx-rest/assets/110108422/0c7302ea-9a42-4759-acbe-057e86c74620)

Might be related to separating bibs/speeches/votes...

**Comment by aaronhelton** [comment]
This appears to be fixed in the current UAT deployment (running v2.10.10)
