### ISSUE TITLE
Truncation in field search

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#1496]
Our manual currently states that 

Truncation (*) is case-sensitive:

991:PALESTIN*

But I get no results when I try that. From #578 it looks like this used to work and I seem to remember that. Did something break?

**Comment by jbukhari** [comment]
Fix pending dlx release v1.4.10 https://github.com/dag-hammarskjold-library/dlx/milestone/10?closed=1
