### ISSUE TITLE
Search match in multiple instances of same field

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#1518]
Not sure if the title makes sense, but basically I want this query to work again:

https://metadata.un.org/editor/records/bibs/search?q=999__a%3A%2F%5E%5Ba-z%5D%7B2%7Dq202408%2F+AND+NOT+999__c%3A%27r%27+AND+NOT+999__a%3Avvc*+AND+NOT+091%3ARES&start=1&limit=250&sort=updated&direction=desc&search=999__a%3A%2F%5E%5Ba-z%5D%7B2%7Dq202408%2F+AND+NOT+999__c%3A%27r%27+AND+NOT+999__a%3Avvc20240813+AND+NOT+091%3ARES&engine=community&format=brief

Copying Joe's comment from the chat:

I'm pretty sure it hasn't changed. The reason it is maybe not giving the results we expect is because the search behavior. If the record has more than one 999 field, then it will still be included in the results for
NOT 999__a:vvc*
because the other 999 fields match. For example, this search returns results
NOT 999__a:vvc* AND 999__a:vvc*
because there are records that have both a 999 = vvc* and a 999 != vvc*

**Comment by jbukhari** [comment]
- [ ] `999__a:vvc* AND NOT 999__a:vvc*` should return zero results

**Comment by jbukhari** [comment]
Pending release of dlx v1.4.15

**Comment by aaronhelton** [comment]
Fixed in #1521
