### ISSUE TITLE
Truncation in logical fields doesn't work

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#1522]
It looks like this might have broken with the latest release:

https://metadata.un.org/editor/records/bibs/search?q=author%3Agerman*&start=1&limit=250&sort=updated&direction=desc&search=author%3Asmi*&engine=community&format=brief

https://metadata.un.org/editor/records/bibs/search?q=bib_creator%3Avvc202409*

We have a related issue in #578 but the truncation in the logical fields used to work until recently. Truncation in fields works as usual.

**Comment by aaronhelton** [comment]
Fixed in #1521
