### ISSUE TITLE
Speech records don't validate

### ISSUE THREAD

**Issue by aaronhelton** [dag-hammarskjold-library/dlx-rest#292]
Because speech records lack a 245 field, but are classed as bib records, they do not validate in the record editor when trying to save. Additionally, the lack of a 245 field prevents adding the record to the basket, which in turn prevents users from sending  a speech record to the editor from the read-only view.

**Comment by jbukhari** [comment]
Marc rule validation, which the Speech records were failing, has been removed from the API code in PR  #296 . It is suggested to implement this in jmarc.mjs instead, and taking into account Vote and Speech records which may have different rules than standard Bib records
