### ISSUE TITLE
Some cloned records can be saved even if there are errors

### ISSUE THREAD

**Issue by aaronhelton** [dag-hammarskjold-library/dlx-rest#315]
When cloning a record, saving the record should fail if there are error messages displayed (e.g., for missing subfield values), but the save is still happening. Unclear if this is limited to auth records or if it also affects bib records.

To reproduce:

1. Open record in editor
2. Click the clone icon
3. Save the record (this should fail because some subfields are blank)
4. In a new tab, view the records for the collection in which the record was cloned
5. One or more cloned records appear in the results, when save should have been skipped

**Comment by jbukhari** [comment]
fixes #315
