### ISSUE TITLE
Prevent creation of duplicate authorities

### ISSUE THREAD

**Issue by aaronhelton** [dag-hammarskjold-library/dlx-rest#372]
It should not be possible to create a duplicate authority record.

Including: When authority records are cloned, saving should be prevented/error out until the record is unique

Need to determine what fields to check for duplication.

**Comment by jbukhari** [comment]
Need clarification

**Comment by aaronhelton** [comment]
Code in branch, not pushed yet

**Comment by aaronhelton** [comment]
Want to be able to duplicate personal names, but not headings of other kinds of authorities. Duplication happens when the 1xx is the same as another record that uses the same tag.

**Comment by aaronhelton** [comment]
Alert on duplication of personal names. Perhaps a confirmation that a duplication would be created, with option to go ahead and create the duplicate.
