### ISSUE TITLE
Include indicator changes in undo/redo

### ISSUE THREAD

**Issue by aaronhelton** [dag-hammarskjold-library/dlx-rest#428]
Indicator changes aren't in the undo/redo vector, so when you change them, the undo and redo buttons have no effect on them.

**Comment by Yalshire2004** [comment]
Yes , I knew that. I just don't implemented the trigger for this particular change.
This feature does not have to be implemented for all the changes event.
e.g: If I am adding a new field it won't trigger the snapshot but trying to define the tag the system will trigger the snapshot.

**Comment by Yalshire2004** [comment]
Anyway, let me know if you really want to implement it for this specific case

**Comment by aaronhelton** [comment]
Fixed in #436
