### ISSUE TITLE
remove x next to the search

### ISSUE THREAD

**Issue by grozdanic** [dag-hammarskjold-library/dlx-rest#456]
Remove the x icon that sits right to the search button;

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/46572480/173124218-5554460a-3bbb-48f6-a8bd-68ab5d7ff79a.png">

ALternativelly add 'magnifying glass icon inside the field instead of search button; just like an x shows inside the search input field now.

**Comment by aaronhelton** [comment]
These two Xs provide different functionality. The one inside the box clears the search text, then disappears. The one outside the box cancels an ongoing search.

An alternative approach could include displaying the "cancel search" option (not necessarily an X) only when a search is still running, and probably next to the spinner. Let's discuss.

**Comment by grozdanic** [comment]
> These two Xs provide different functionality. The one inside the box clears the search text, then disappears. The one outside the box cancels an ongoing search.
> 
> An alternative approach could include displaying the "cancel search" option (not necessarily an X) only when a search is still running, and probably next to the spinner. Let's discuss.

ok, noted... but imo users will not use them .. you press ESC to stop the search or clear/paste the field .. less is better ..

**Comment by viola-v** [comment]
The X in the search box has been removed, closing.
