### ISSUE TITLE
Carry over some indicators from auth record to bib record 

### ISSUE THREAD

**Issue by aaronhelton** [dag-hammarskjold-library/dlx-rest#461]
The first indicator of the following authority-controlled fields in the bib record should be carried/copied over from the corresponding first indicator in the authority record: 

600 (from 100) 

610 (from 110) 

611 (from 111) 

700 

710 

711 

991 => this is the only instance where the indicator has useful meaning attached, it identifies whether the agenda item belongs to the GA, ECOSOC or the Security Council. And it might be used in the ITP scripts – something to check! 

 

Optional, if not too much work: 

The second indicator for all 6XX fields should automatically be set to “7”.

**Comment by viola-v** [comment]
Just looked back at the discussions I had with Valeria on this one - for now we do need to keep and carry over the first indicator for the agenda items (991 in the bib record).

So when this authority record is selected in the authority lookup in the bib record:

![image](https://user-images.githubusercontent.com/110108422/186195343-d5951a85-f8eb-45d8-8036-42468c87c83e.png)

it should look like this in the bib record:

![image](https://user-images.githubusercontent.com/110108422/186195555-bbdfef98-7048-459a-97b6-df09d5e64786.png)

That is the first indicator (3 in this case) should be copied over from the authority record and added to the field when the authority is selected.

**Comment by viola-v** [comment]
Reopening this because as it was implemented, **all** indicators are carried over instead of **some** as specified above.

I think we really only need it for 991 at this point, so it would be great if we could change the implementation.
