### ISSUE TITLE
Allow selection of no record view in edit user profile

### ISSUE THREAD

**Issue by jbukhari** [dag-hammarskjold-library/dlx-rest#509]

**Comment by aaronhelton** [comment]
Best practice for option selectors where one option can be None is to either spell out the None option in the list or to have a blank row in the option list. In both cases this should remove existing options on save or save with a blank option set.

As a workaround, we can use CTRL+Click on Windows and Linux, and CMD+Click on Mac, to unselect the current selection. Saving will remove it from the option set in the user profile.
