### ISSUE TITLE
Option to display all results in search/and browse

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#517]
This came from Valeria, she wants the option to see all results without having to click previous/next - I think we might have to discuss further to find out what the actual user need is.

**Comment by aaronhelton** [comment]
Need to determine what can be satisfied with reports, what can be accommodated by increasing the total results displayable at a time (5000? 10000?), and what would need an infinite scroll.

**Comment by aaronhelton** [comment]
Let's start by increasing the number of results per page (adding more/higher options: 1,000 and 5,000)

**Comment by aaronhelton** [comment]
Oh, I see this was fixed in #528
