### ISSUE TITLE
Option to select all search results and add to the basket

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#518]
This is actually a very common task, I run a search and need to edit all the results, so I need a quick and easy way to add all records to my basket rather than clicking on them individually.

**Comment by aaronhelton** [comment]
Checkboxes (one -> all (any limits?) -> none)

And/or a single option to send all to basket

**Comment by aaronhelton** [comment]
Let's limit this to 500 records. Too many records in this option will create performance problems or risk timeouts. We can start with this limit and adjust up or down depending on performance and balancing user needs.
