### ISSUE TITLE
Need to see who created/updated record last other than manual entry in 999

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#519]
We cannot just rely on people entering their initials manually in 999, we need to preserve this Horizon function and be able to see who touched the record last: 
![image](https://user-images.githubusercontent.com/110108422/181266274-c544267d-3abc-49f6-a04b-d0d0653cd8e3.png)

Currently this information is exported to a 998 field:
![image](https://user-images.githubusercontent.com/110108422/181266474-e1ee69e2-a54d-498c-9e41-e2a8fd0217d9.png)

The information in 998 is currently also used for statistics via these queries in the DL: [https://unitednations.sharepoint.com/:w:/s/DGC-OutreachD/ERYWNkgENaRMncxnNKDcQuMB42fWoeUREjr6yGSFVI9CLg?e=ctR9ZC](url)

Maybe it can be added to 998 when the user clicks save?

Also related to issue #349.

**Comment by viola-v** [comment]
So this did come up in today's training session. The information is available in the record history, and I will seek feedback from colleagues to see if that is enough, or if we need to see it directly in the record.

We also need to be able to run queries based on record creation and last update date for statistical purposes. It's currently done via 998 and that's very convenient and easy to do. To discuss further...

**Comment by aaronhelton** [comment]
Relies on #349
