### ISSUE TITLE
Fix workform titles

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#524]
Not crucial for testing, it just doesn't look good - could someone remove all the special characters from the workform titles in UAT?

![image](https://user-images.githubusercontent.com/110108422/181361642-d5e6f1e3-b423-45e6-a5f2-af80159187b0.png)

**Comment by aaronhelton** [comment]
I was wondering about these. Any idea where they came from?

**Comment by viola-v** [comment]
I had created them, but the names were NY_bib_straight, NY_bib-pub-sym, NY_bib_pub_unsym and NY_bib_non-straight. I don't remember, but I think I might have created them in QAT and then they were moved to UAT and that's when this happened? Anyway, if it's too much of an issue I can just recreate these templates, but I don't think we have anything on the UI that allows us to delete workforms?

**Comment by aaronhelton** [comment]
These are the less than and greater than brackets. No idea how they were introduced, but I took them out.

**Comment by aaronhelton** [comment]
This should be fixed, anyway. I am closing it, but if there are more issues to address, we can reopen it.
