### ISSUE TITLE
Clarify what is included in heading search (Advanced Search, authorities)

### ISSUE THREAD

**Issue by aaronhelton** [dag-hammarskjold-library/dlx-rest#534]
![image](https://user-images.githubusercontent.com/617997/183079574-28c79bf0-4e6d-4d4a-8db9-3a814587e103.png)

**Comment by aaronhelton** [comment]
This could be addressed in the search guide/documentation.

Change the name from heading to subject in the dropdown list. See also #529

**Comment by viola-v** [comment]
This is what we have in the DL - do we want the same for the ME?

![image](https://user-images.githubusercontent.com/110108422/187224756-bf8411f2-0778-44ab-8e7d-5c335f1c4f13.png)
