### ISSUE TITLE
Create a space in the app for help/documentation

### ISSUE THREAD

**Issue by aaronhelton** [dag-hammarskjold-library/dlx-rest#541]
We need a place in the app to host documentation.

Embed research guides? --> Preferred approach.

**Comment by aaronhelton** [comment]
See: https://github.com/dag-hammarskjold-library/metadata-un-org/blob/master/metadata/thesaurus/templates/_thesaurus_about-en.html for an example of how this is done with LibGuides.

**Comment by viola-v** [comment]
@aaronhelton Here's the link to the LibGuide Ashley created: https://research.un.org/marceditor Please let me know if you need anything else from our end!
