### ISSUE TITLE
Browse: sorting of agenda records

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#550]
Agenda records don't sort properly in Browse: 
![image](https://user-images.githubusercontent.com/110108422/184163753-aed04bd3-9c96-4cf5-8b92-420803286490.png)
It should be 3, 3a, 3b, 4, ... 30, 31a,...

There can also be square brackets in $b (but they seem to sort properly): 
![image](https://user-images.githubusercontent.com/110108422/184164141-e205ff0c-0649-4e2e-ade9-caf0959489b1.png)

Possibly related to #544.

**Comment by aaronhelton** [comment]
Fixed in #617
