### ISSUE TITLE
No more warning/alert when trying to close a record with unsaved changes

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#555]
This is currently happening in QAT - I can make changes to a record and close it without getting an alert that there are unsaved changes.

**Comment by aaronhelton** [comment]
This should just be a matter of adding a saved state check on the close record function:

https://github.com/dag-hammarskjold-library/dlx-rest/blob/master/dlx_rest/static/js/record.js#L1353
