### ISSUE TITLE
Add a copy selected fields control to the record editor

### ISSUE THREAD

**Issue by aaronhelton** [dag-hammarskjold-library/dlx-rest#556]
Clicking the checkbox next to fields currently adds the field contents to the copy/paste stack. This creates unwanted interactions when, e.g., deleting fields, so pasting includes the deleted fields.

We should instead use a control to "copy selected fields" which can then be pasted using the paste icon.

**Comment by aaronhelton** [comment]
- Also clear and create a new copy/paste stack each time the control is invoked.

**Comment by jbukhari** [comment]
This may not be necessary, since the paste functions works by only pasting fields currently checked

**Comment by aaronhelton** [comment]
Yeah, this shouldn't be necessary anymore given #558 so I'll close it out.
