### ISSUE TITLE
Record view - cannot go back to "all fields" view when default view defined in user profile

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#569]
When I'm logged in as a user with a View defined in my user profile, I don't have the option to change the view in the editor: 
![image](https://user-images.githubusercontent.com/110108422/184881770-fe62fe04-8b5e-49ab-a1ef-dddeaffb4242.png)

Instead of showing the "filter" icon, I should see the "x" icon that allows me to go back to the "all fields" view (this is what it looks like when I'm logged in as a user without a default view in the user profile): 
![image](https://user-images.githubusercontent.com/110108422/184882057-c525f082-33ea-422b-b093-859eb5f04f6f.png)

**Comment by aaronhelton** [comment]
Add an "All Fields" view so you can see all of the fields as one of the views.
