### ISSUE TITLE
Newly created/saved record doesn't disappear from editor when deleted

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#573]
I create and save a new record, but when I try to delete it, I get an error message, and the record stays in the editor. The record does get deleted (I don't see it when I look for it), but it shouldn't remain in the editor. I don't remember this happening in QAT...

https://user-images.githubusercontent.com/110108422/184980208-590fc248-64c6-483f-a6b5-340ac3c0ab62.mp4

**Comment by aaronhelton** [comment]
The source of this error seems to be down in jmarc.mjs, where the delete method is attempting to catch an invalid constructor name.
