### ISSUE TITLE
Record doesn't show up in search index even though it exists in CDB

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#580]
This is the record: https://digitallibrary.un.org/record/1637848/export/hm

![image](https://user-images.githubusercontent.com/110108422/185467257-4d1f9fb4-082b-419a-8ae2-72602edf78a2.png)

**Comment by aaronhelton** [comment]
Need clarification: where did this occur?

**Comment by viola-v** [comment]
This seems to be ok now.
