### ISSUE TITLE
Sorting by more than one criteria

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#581]
Mentioned as useful as part of search test feedback (it's something that Horizon does).

**Comment by aaronhelton** [comment]
Probably doable, but will need some additional interface options to support it.

What is the overall outcome of this? Is this more of an analytics or reporting feature?

**Comment by JoelleSciboz** [comment]
For speech records display and sort by columns:
Meeting record symbol  / Meeting date / Speaker / Country/Organization

For bib records display and sort by columns: 
Title / Pub date / Author / Doc symbol

**Comment by viola-v** [comment]
We implemented this for the speech review section, not sure that it's necessary for bibs. Closing this for now.
