### ISSUE TITLE
Dashes in search terms are interpreted as negation and cause unexpected results.

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#582]
This search works: 239:"compilation document of the statements delivered by Heads of State"

This doesn't (even though there are results): 239:"compilation document of the statements delivered by Heads of State or other dignitaries by means of pre-recorded"

**Comment by aaronhelton** [comment]
The dash in this title is causing the issue.

**Comment by aaronhelton** [comment]
Short term: Ignore dash between quotation marks; check for space before dash to preserve expected syntax.

**Comment by viola-v** [comment]
@jbukhari The example I used still doesn't work.

This works: 
![image](https://user-images.githubusercontent.com/110108422/192350807-b6b31298-90e0-4ceb-8847-305830b4fd5f.png)

This one still doesn't: [239:"compilation document of the statements delivered by Heads of State or other dignitaries by means of pre-recorded"](https://2v19pwdi0h.execute-api.us-east-1.amazonaws.com/qat/records/bibs/search?q=239%3A%22compilation+document+of+the+statements+delivered+by+Heads+of+State+or+other+dignitaries+by+means+of+pre-recorded%22)

Trying to find this: 
![image](https://user-images.githubusercontent.com/110108422/192351078-755795f5-9167-4300-a4eb-bb17d8f33a8b.png)


Is there something other than the dash that's causing problems?
