### ISSUE TITLE
Record view options have disappeared

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#599]
When I click on the record view icon in the bib record (the filter), I get this pop-up: 
![image](https://user-images.githubusercontent.com/110108422/186200481-556058e4-8732-4dfc-a85c-0c3ee713e810.png)

It looks like it's related to merging authorities?

**Comment by aaronhelton** [comment]
See: https://github.com/dag-hammarskjold-library/dlx-rest/blame/46678768eac2f67c32b3bf503c4ddcb9ba52c748/dlx_rest/static/js/record.js#L109
