### ISSUE TITLE
Authorities look-up: enable free text search

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#604]
Currently the search looks for a phrase, meaning if you’re looking for example for this authority “UN. Special Representative of the Secretary-General and Head of the United Nations Support Mission in Libya”, you have to enter something like “Head of the United Nations Support Mission in Libya” to get the result: 

 

Searching for “special head libya” currently doesn’t work, but it should.

**Comment by jbukhari** [comment]
@viola-v Note: the typeahead lookup currently matches partial words, whereas "free text" search does not. For example, in typeahead lookup, typing "hammar" matches "Hammarskjöld" but in free text search, the whole word has to be matched. Are we OK with losing the partial word match? As such it would no longer be typeahead functionality but rather a standard search.

**Comment by viola-v** [comment]
@jbukhari I discussed this with Ashley and Susan and we think that the free text search will serve our needs better. We have so many authorities consisting of several words, and it seems like the free text search would make it easier to find them.

**Comment by viola-v** [comment]
Upon further thought I'm wondering how well the free text search would work for the 191 and 991 fields, which contain symbols. Would it be possible to keep the look-up function for these and only change it to free text for the 6XX and 7XX fields?

**Comment by jbukhari** [comment]
Will try to leave the existing functionality in place while adding the alternate option
