### ISSUE TITLE
Add subfields automatically based on Marc field

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#608]
In Horizon, if you enter a new Marc field, several empty subfields are added automatically, which saves time. Here are a few examples from Horizon - I only entered the Marc field, and the empty subfields appeared automatically (and in one case the subfield has been prepopulated with a value):

![image](https://user-images.githubusercontent.com/110108422/186485407-a7ce8da5-527f-4435-859c-6644fe99da1f.png)

This is connected to validation, where all valid subfields are defined, but not all valid subfields are added automatically.

**Comment by aaronhelton** [comment]
Need field and subfield specifications for this.

**Comment by viola-v** [comment]
I've added the specs to the validation documents in yellow - whenever the default subfield should not be $a, I made a note which subfields are supposed to be used:

![image](https://user-images.githubusercontent.com/110108422/186976743-b134bfee-ce50-4381-95e5-4ea82d3a8c18.png)

Bibs:[https://unitednations.sharepoint.com/:w:/s/MarcEditorProject/EVHcCTwbWhJLny6R76i3MJ0Bk6nwfq1MKGWb23pO9kv_4Q?e=WufmiT](url)

Auths: [https://unitednations.sharepoint.com/:w:/s/MarcEditorProject/ETZy0fYB0P1MsogXr_ECrgUBfuFDa-VfyAKYXUYfQgM7NQ?e=dg9AXD](url)

Speeches: [https://unitednations.sharepoint.com/:w:/s/MarcEditorProject/EVqcJvcxsixFv6NZ6Vo_fogBt5K6tXZ2Q_Leh4lvh8vcKQ?e=TKU7iw](url)

Votes: [https://unitednations.sharepoint.com/:w:/s/MarcEditorProject/Ec7hcVPc_DdBsa8UDKlSmwUBwLIkZFv1fV51_4z8PTBkDg?e=2ktHcL](url)
