### ISSUE TITLE
Allow records to be saved with empty subfields and delete those fields upon save

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#609]
The MarcEditor currently gives an error message if you're trying to save a record with an empty subfield. Horizon deletes an empty subfield when the record is saved, we want the same functionality in the MarcEditor.

**Comment by aaronhelton** [comment]
If the field/subfield is required but empty, throw an error, but otherwise exclude empty fields/subfields from the save action.
