### ISSUE TITLE
Usability: navigating through Marc field is cumbersome

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#610]
I made a video to show what's going on, I have to click a lot more than in Horizon to get where I need to be:

https://user-images.githubusercontent.com/110108422/186488156-6f195fd6-2399-42dc-acd7-35229a28e9f6.mp4

This is also related to #608.

**Comment by aaronhelton** [comment]
This needs more analysis, but is otherwise a pressing issue.

**Comment by viola-v** [comment]
The video is not up-to-date anymore, improvements have been made.
