### ISSUE TITLE
Use the checkbox in front of a field to select multiple fields for deletion

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#615]
Self-explanatory, we just need to figure out an icon for that - it cannot be the trash bin since that's for deleting the record.

Ideally you would also be able to delete several selected fields with the shortcut Ctrl + k (delete field).

**Comment by aaronhelton** [comment]
We would need to find an icon we can use, then place it in the record control set.

**Comment by aaronhelton** [comment]
Can we use the same keyboard shortcut to delete the multiple selected fields?
