### ISSUE TITLE
Record Editor: Closing a record doesn't automatically select the remaining record on the screen

### ISSUE THREAD

**Issue by aaronhelton** [dag-hammarskjold-library/dlx-rest#626]
This happens when two records are open in the editor.

https://user-images.githubusercontent.com/617997/187219754-afdb04f9-0021-4703-bfb2-d40e6cbe7b5d.mp4

Also it takes a second or so to close, causing some browsers to complain about a click violation.

And finally, as you can see in the recording, the remaining record is rendered with focus in the middle of the record.

**Comment by viola-v** [comment]
Doesn't seem to work in Edge...

**Comment by jbukhari** [comment]
Upon further review, it's jot related to the browser. It works when closing first record but not the second.

**Comment by jbukhari** [comment]
Further further review: it works when using the keyboard shortcut (esc) to close the record, but not when clicking the close record button

**Comment by aaronhelton** [comment]
Fixed by #771
