### ISSUE TITLE
Undo/redo is not working correctly

### ISSUE THREAD

**Issue by aaronhelton** [dag-hammarskjold-library/dlx-rest#628]

**Comment by Yalshire2004** [comment]
For this kind of bug, we need at least a video or a text to explain the case.

**Comment by viola-v** [comment]
Undo/redo doesn't seem to work for:

- moving subfields up or down
- deleting one or multiple fields
- deleting more than one character of text

https://user-images.githubusercontent.com/110108422/195159689-9f7d8044-703f-48c8-9b1b-6f06c85d457b.mp4

**Comment by aaronhelton** [comment]
Fixed by #746
