### ISSUE TITLE
Deleting/flagging extra space in text/add end of field

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#650]
From Valeria:

_It would be very helpful and save staff a lot of time that any extra spacing within text, and empty characters at the end of the field, could be highlighted with another color (maybe green). It should be highlighted only where the extra spaces are.

Applied to all records (bib, speech, voting and authority records (including agendas)).
Applied at the time of creation of a record and when displaying/opening and older record._

I think some of this has come up and has been fixed already. For example, extra spaces in a field were often created by copying and pasting something with a line break - Horizon would turn the line break into an extra space. And I think we had discussed not allowing empty spaces at the end of a field in the context of validation. I assume we could also add a rule for more than one space within the text? 

This wouldn't solve the issue of old records having these issues - for that the suggestion to highlight these in the display might work. Or - and probably even better - a batch fix down the road?

**Comment by aaronhelton** [comment]
Also double spaces.
