### ISSUE TITLE
190 headings don't display in Auth simple search when sorted by heading

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#682]
This is in [UAT](https://fl1dehj4m7.execute-api.us-east-1.amazonaws.com/uat/records/auths/search?start=1&limit=25&sort=heading&direction=asc&q=190%3A*&format=brief): 
![image](https://user-images.githubusercontent.com/110108422/191598991-a32dcd11-843f-4da0-b56e-f7edba7f877f.png)

There are results, but none display...

They do display if [sorted by updated](https://fl1dehj4m7.execute-api.us-east-1.amazonaws.com/uat/records/auths/search?start=1&limit=25&sort=updated&direction=desc&q=190%3A*&format=brief)...

**Comment by aaronhelton** [comment]
The heading sort is missing 190 $b and $c.
