### ISSUE TITLE
Sorting of subfields

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#692]
It looks like the order of subfields in existing records changes in the MarcEditor. For example, this record in Horizon has subfields $g and $t in a specific order that mirrors the structure of the publication:

![image](https://user-images.githubusercontent.com/110108422/192294250-ba8f3a98-b922-41b1-9272-4346ed2a8287.png)

The fields also display in this order in the [DL](https://digitallibrary.un.org/record/3846848?ln=en).

This is from the [LoC Marc manual](https://www.loc.gov/marc/bibliographic/bd505.html):

![image](https://user-images.githubusercontent.com/110108422/192294708-49565853-6083-426a-b16e-6a8887543b40.png)

In the MarcEditor the record looks like this - no changes have been made (as far as I can tell), so I assume the fields always display in alphabetical order?
![image](https://user-images.githubusercontent.com/110108422/192294930-e75a96b7-25e3-47c4-8a53-fd29d00eb6f7.png)

However, they don't do that for the title, there the original order of the fields is preserved:

![image](https://user-images.githubusercontent.com/110108422/192295196-c9dd345f-fa26-4043-ae26-0e7a5301f119.png)

Overall subfields should display in their original order (as they were in Horizon), and when new subfields are added, they should be saved as it, with no sorting applied.

**Comment by jbukhari** [comment]
Are the subfields in the correct order here? https://td1ljyw4rd.execute-api.us-east-1.amazonaws.com/prod/api/marc/bibs/records/1244453?format=mrk

That is a direct representation of what is in the production database, so the reason I ask is in order to determine if the order is being saved correctly in the initial Horizon -> central DB transfer

**Comment by viola-v** [comment]
> @viola-v Are the subfields in the correct order here? https://td1ljyw4rd.execute-api.us-east-1.amazonaws.com/prod/api/marc/bibs/records/1244453?format=mrk
> 
> That is a direct representation of what is in the production database, so the reason I ask is in order to determine if the order is being saved correctly in the initial Horizon -> central DB transfer

Yes, the order is correct!

**Comment by jbukhari** [comment]
Subfields are being reordered in Jmarc.parse() https://github.com/dag-hammarskjold-library/dlx-rest/blob/b21573178acfc0e78999fed1c9fdde27256b66a2/dlx_rest/static/js/jmarc.mjs#L608

**Comment by viola-v** [comment]
I tested this again just now, and the fields do initially save in the correct order, but then if you open the record again, it reverts back to alphabetical order (but you might know that already):

https://user-images.githubusercontent.com/110108422/193107348-cf72cb55-96e9-424e-9004-a0b1234e5220.mp4
