### ISSUE TITLE
Alphabetical sorting to exclude special characters like parentheses and quotation marks

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#693]
Currently, the sorting includes special characters so we have to know that they are there in order to find the correct records. For example, I can no results when I browse for the title "hitting the ground":

![image](https://user-images.githubusercontent.com/110108422/192298510-28e30d64-4788-426a-bc8a-54807c1e4069.png)

I need to know that this particular title starts with parentheses:

![image](https://user-images.githubusercontent.com/110108422/192298647-9275758e-f1b6-44a7-b7fb-add7494e2e9c.png)

Alphabetical sorting should exclude special characters like parentheses and quotation marks.

**Comment by aaronhelton** [comment]
We can ignore the character, but there are questions on what will be displayed.
