### ISSUE TITLE
Alphabetical sorting to exclude punctuation

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#694]
Currently, browsing requires you to know punctuation within the field. For example, I'm looking for the Human Development Report 2020:

![image](https://user-images.githubusercontent.com/110108422/192299438-5d766e7f-f125-49bc-af10-d554585e7764.png)

I only get the correct result if I use a period:

![image](https://user-images.githubusercontent.com/110108422/192299604-1639b71f-582a-4557-9e87-1758b9818915.png)

Ideally I would not have to enter punctuation to get the proper results.

**Comment by jbukhari** [comment]
A solution was identified but rejected. The solution allows for ignoring punctuation, but apparently not without ignoring spaces. Ignoring spaces is not desirable, as it yields unexpected sort orders. That is especially apparent with personal names. MDB collation: https://www.mongodb.com/docs/manual/reference/collation/

Alternate solutions may be possible with further review.

**Comment by viola-v** [comment]
Maybe Atlas can help?

**Comment by jbukhari** [comment]
Closed by #1265
