### ISSUE TITLE
Sorting direction (asc/desc) missing depending on screen size

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#697]
On my laptop, at 100% zoom, the sorting direction is missing when I look at Speeches:

![image](https://user-images.githubusercontent.com/110108422/192348417-63444262-2dd7-46b2-ad3f-9ba696a77583.png)

In bibs, it's partially cut off: 
![image](https://user-images.githubusercontent.com/110108422/192348587-733a5751-0c94-4571-95fb-21b90b0b7ecc.png)

The DL hides these options by default, which I don't like. 

Maybe we can move the descriptions (Results per page, Sort and Directions) on top of the columns?

**Comment by aaronhelton** [comment]
This has to do with break points for the elements in question.
