### ISSUE TITLE
Authority record that was updated shows up in browse index with both new and old heading

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#701]
Earlier today I updated this authority in QAT, I removed a period at the end of the name:

![image](https://user-images.githubusercontent.com/110108422/192633307-2ffcb7a6-edbb-4a46-871c-ac9e156fc515.png)

Now two authorities show up in the browse list, the updated one, but also the original one with the period:

![image](https://user-images.githubusercontent.com/110108422/192633471-8f6a6748-7685-4b52-97ea-d02e5f3c52f7.png)

When you click on the original one, there is no authority record, instead this page opens:

https://2v19pwdi0h.execute-api.us-east-1.amazonaws.com/qat//records/auths/search?q=subject%3A%27Smith%2C+Ben.%27

Does this have something to do with the browse indexes not updating right away?

**Comment by aaronhelton** [comment]
May be fixed, needs testing.

**Comment by viola-v** [comment]
Trying another example in QAT:

original record:
![image](https://user-images.githubusercontent.com/110108422/193357767-e4ecf282-2f6e-4015-a17d-e7266985bd67.png)

updated:
![image](https://user-images.githubusercontent.com/110108422/193357832-778be12d-25d2-46d4-a481-f3fd92cc8993.png)

Browse list shows both the original one and the updated one:
![image](https://user-images.githubusercontent.com/110108422/193357947-7d2edb76-eed3-4226-8aa2-4e39595084cf.png)

And one more:

Original browse list:

![image](https://user-images.githubusercontent.com/110108422/193358019-5bf7d0b5-9339-497c-97c8-f34054b37dc9.png)

Original record:
![image](https://user-images.githubusercontent.com/110108422/193358052-c349b57a-2189-4d53-996a-b47a0ffc9463.png)

updated record:

![image](https://user-images.githubusercontent.com/110108422/193358101-3eeae8b2-b43e-43b8-8aec-56b6b5fcf894.png)

New browse list:
![image](https://user-images.githubusercontent.com/110108422/193358144-91613bea-9963-4eb4-98ac-6ed329de27ad.png)

So this is not something that has been fixed by recent updates and needs to be looked into.
