### ISSUE TITLE
Logical fields behind auth browse indexes

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#702]
We're getting confusing results for the auth browse indexes:

Browsing for "smith, a" in subject, we get the following:

![image](https://user-images.githubusercontent.com/110108422/192634070-24204041-70e7-4eb5-bf42-1b2f152d7156.png)

When browsing for the same term in author, "Smith, Adam" is missing:

![image](https://user-images.githubusercontent.com/110108422/192634302-828d7278-ceb3-4b55-80d1-ac68de1de2ed.png)

According to the [logical fields documentation](https://unitednations.sharepoint.com/:x:/r/sites/MarcEditorProject/Shared%20Documents/General/Logical%20fields.xlsx?d=wd1dc25b6e4b04f69bc6aead188f3bdd9&csf=1&web=1&e=y3Apzr), both subject and author in the auth browse should include 100, so we should get the same results.

**Comment by aaronhelton** [comment]
Look for additional examples.

**Comment by viola-v** [comment]
Here's another example:

Smith, Courtney B. only shows up in auth/author browse, but not auth/subject browse:

![image](https://user-images.githubusercontent.com/110108422/193358540-277b1392-ebd3-4ff7-bc2a-d378259bdaca.png)

![image](https://user-images.githubusercontent.com/110108422/193358549-326afde1-acf2-447d-82db-c04760903fd9.png)


And here's an example of a 110:

![image](https://user-images.githubusercontent.com/110108422/193358694-20753c5a-41c5-4ff6-8b8e-8581a6757341.png)

![image](https://user-images.githubusercontent.com/110108422/193358749-34740bde-4313-4766-af76-4a8586c650d7.png)

What logical fields do the browse indexes for auth/subject and auth/author look into? According to the [requirements](https://unitednations.sharepoint.com/:x:/r/sites/MarcEditorProject/Shared%20Documents/General/Logical%20fields.xlsx?d=wd1dc25b6e4b04f69bc6aead188f3bdd9&csf=1&web=1&e=y3Apzr) it should be as follows:

![image](https://user-images.githubusercontent.com/110108422/193358922-777430b1-68ea-4815-b264-1cbdc35fe78a.png)

![image](https://user-images.githubusercontent.com/110108422/193358961-07758262-ee9c-403a-b8a4-2f60067914a2.png)
