### ISSUE TITLE
Cloned record not displayed when two records are already open

### ISSUE THREAD

**Issue by jbukhari** [dag-hammarskjold-library/dlx-rest#706]

**Comment by aaronhelton** [comment]
Workaround is to close one of the records before trying to clone the other.

**Comment by aaronhelton** [comment]
More immediately: Add a warning to let users know what happened.

**Comment by viola-v** [comment]
This has been fixed - when I have two records open and clone one of them, the one that's being cloned disappears, and the clone and the other records are still open.
