### ISSUE TITLE
Wording on close record

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#731]
Related to the implementation of #658 

This is what it currently looks like: 

![image](https://user-images.githubusercontent.com/110108422/195145951-29ca9842-4b0f-4fca-8cbf-aea9a18a95e1.png)

"Save" makes sense to me.

"Save and release" - I think "release" is not intuitive. Maybe "Save and close"?

"Close and discard" - I'm not sure if this option is necessary or even useful. To discuss...

"Cancel" is fine.

**Comment by aaronhelton** [comment]
Re: Close and Discard: If you don't have this option, you have to either save or undo all your changes before you can close the record. While this may be the desired behavior for most purposes, if you're trying to demonstrate something that you don't want to save, if you don't have a close and discard option, your only way to discard your unsaved changes is to navigate away from the page. I recommend keeping this option and making sure the wording makes sense.

**Comment by jbukhari** [comment]
Suggestions: "Save and close, "Save and remove from basket", "Close without saving", "Cancel"

**Comment by viola-v** [comment]
This came up again as part of UAT testing, to be revisited!
