### ISSUE TITLE
Sorting results with symbols by relevance is invalid search?

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#808]
Not sure if this is a known issue - you cannot sort symbols by relevance?

![image](https://user-images.githubusercontent.com/110108422/204337402-726f4462-96ef-41c9-8c74-62979c04c29d.png)

**Comment by jbukhari** [comment]
At this time, sorting by relevance only works on all-fields free text search

**Comment by viola-v** [comment]
What exactly is an all-fields free text search?

**Comment by viola-v** [comment]
Sorting by relevance is probably not something that we do very often - if ever...
