### ISSUE TITLE
5 digit date in 269 and 992

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#812]
I picked a random record and I entered a five digit date in 269 and 992, there's no validation warning:

![image](https://user-images.githubusercontent.com/110108422/204578362-49c63a22-4ef4-4afa-a5b9-a480faafef36.png)

And I can save the dates as they are, the dash doesn't get added:

![image](https://user-images.githubusercontent.com/110108422/204578585-3588305d-b80f-4fda-b03e-f43d39bbd6c1.png)

**Comment by aaronhelton** [comment]
Closed with #814
