### ISSUE TITLE
989 duplication

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#821]
I just cloned a record that already had a 989, then added another 089 field with a different value, and when I save the record, an additional 989 field was created:

![image](https://user-images.githubusercontent.com/110108422/204918286-4ca9649f-3f21-4bea-8485-8c6a341348bd.png)

I think in general we want another field to be added if the there is a logic behind it, but in this case it doesn't make sense to have a 989 field with subfields $a and $b, and another field that just has $a.

**Comment by JoelleSciboz** [comment]
To close - solved: #960 and #523
