### ISSUE TITLE
981 logic

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#822]
Can we go over the logic for creating 981? It seems to work fine for some bodies (Trusteeship Council for example), but not others (General Assembly)...

**Comment by viola-v** [comment]
Here are two examples of records created as part of testing that have the wrong value (Trusteeship Council): 

http://54.87.252.103/uat/editor?records=bibs/1361499
http://54.87.252.103/uat/editor?records=bibs/1361500

**Comment by viola-v** [comment]
Jessica confirmed that new CAT documents she indexes all have the Trusteeship Council as 981 in addition the the correct one. As far as I can tell, this doesn't seem to be happening to the data in the DL...

**Comment by viola-v** [comment]
This is under 981 in the validation file: https://github.com/dag-hammarskjold-library/dlx-rest/blob/0eb773686ce6ed1d940cd743b53370ccb933734a/dlx_rest/static/js/validation.js @JoelleSciboz and I will review!

**Comment by viola-v** [comment]
@jbukhari I wonder if the issue is that we need regular expressions for the queries?

For example, this rule gets applied to records with 191__b:CAT/C, which it shouldn't: 

"191__b:T/* OR 791__b:T*": {"c": null, "b": null, "a": "Trusteeship Council"} 

A record that has 191__bST/DPI/PRESS/SG/SM/ also gets this rule applied which again it shouldn't:

"191__b:S/* OR 791__b:S*": {"a": "Security Council", "c": null, "b": null},

So we need to say that the symbol has to start with T/ to get the proper results. And we should apply it to all queries, because we have all kinds of symbol combinations that could get wrong applied if we aren't precise here.

This doesn't happen in the DL, so the queries work differently there it seems.

**Comment by JoelleSciboz** [comment]
@jbukhari This rule:
symbol:/^A\\/([1-9]|DEC|RES|BUR|PV|INF|SR|ES-|S-)/": {"b": "General Assembly Plenary", "c": null, "a": "General Assembly"} could it be because we use the logical field?

**Comment by JoelleSciboz** [comment]
The other issues was already reported by Viola, but here are some more findings. If we don't use the regular expression in our query, then the rule is applied on records with Symbol starting by or records with the string anywhere in the symbol.
"191__b:S/* OR 791__b:S*": {"a": "Security Council", "c": null, "b": null}
- Is applied correctly to all Security Council records 
- Is applied incorrectly to other records with a S/ in the symbol for instance the following document got the 981 for Security Council: [E/ECE/]CES/AC.71/2004/19(Summary)

**Comment by JoelleSciboz** [comment]
[981_testing.docx](https://github.com/dag-hammarskjold-library/dlx-rest/files/10320330/981_testing.docx)
Result of testing all the conditions in rules 981
