### ISSUE TITLE
Autofill 040 in authorities

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#832]
Is there a way when inputting the 040 field in an authority that it can be autofilled with the correct metadata, as happens in Horizon?  For older authorities, the 040 is often not included and it means inputting metadata for 3 subfields each time. $a NNUN $b eng $f unbisn

![image](https://user-images.githubusercontent.com/110108422/205718773-8b424ca7-421b-485a-9c5b-4b548575cf52.png)

This could also apply to bib records. And we could consider the same mechanism for 905 in the auth records.

Could potentially done based on user profile. To be discussed and prioritized...

**Comment by jbukhari** [comment]
@viola-v First, are we sure that we even need these fields? If so we could add the field on record load. Or, we could create a new configuration that goes with the default subfields for default values. So if you add a field with default subfields, it also adds the default values (if any).

**Comment by viola-v** [comment]
We currently run statistics based on 040 ($a) - it allows us to easily distinguish between records created by DHL or UNOG, and that is something we want to keep going forward. So the default values would have to change depending on whether someone from DHL or UNOG creates these records.

**Comment by JoelleSciboz** [comment]
Covered by #981 I'm closing this.
