### ISSUE TITLE
650 $2 - suppress from view

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#835]
Somewhat similar to 710 $9, we don't need/want to see 650 $2 in the bib records, it just takes up space and doesn't add anything. Unlike 710 $9, the subfield is correct and for all the old records it is there in Horizon as well, but we won't add it to new records, so I think suppressing it from the default view would be helpful.

**Comment by aaronhelton** [comment]
This also applies to other fields: all the 600s, etc.

**Comment by JoelleSciboz** [comment]
No change in the ME needed, we will delete these fields altogether.
