### ISSUE TITLE
Don't prompt about unsaved changes when opening/downloading files

### ISSUE THREAD

**Issue by aaronhelton** [dag-hammarskjold-library/dlx-rest#843]
Currently when a record has unsaved changes, clicking the "download" button will trigger the window-level "leave/stay" confirmation prompt. This is due to the "beforeunload" event firing incorrectly. It can be solved by adding a download="true" attribute to the link tag for the file download.

**Comment by jbukhari** [comment]
Let's establish what is supposed to happen when clicking either option
