### ISSUE TITLE
Sorting by title issues

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#852]
I'm looking at an auth record and I click on the link for the linked bib records:

![image](https://user-images.githubusercontent.com/110108422/206293163-b587256d-2eb8-4583-8bb7-c46620408399.png)

I should get four results, but none show up, because I had sorted a previous search by title and these are all speech records, which don't have titles:

![image](https://user-images.githubusercontent.com/110108422/206293337-e6f12c1a-e789-48a7-9353-3ea40bb5fc7c.png)

This is unexpected and confusing behavior for the user, but I'm not sure how we can fix it...

**Comment by jbukhari** [comment]
We should probably exclude speech and voting records from "normal" search

**Comment by aaronhelton** [comment]
Proposal: Include results that don't have the field being sorted by.
