### ISSUE TITLE
Number of results wrong when sorting by symbol

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#853]
This [search](http://54.87.252.103/uat/records/bibs/search?start=1&limit=1000&sort=symbol&direction=asc&q=xref%3A371830&format=brief) says it has 17 results, but the list contains a lot more than 17 records when I sort by symbol:

![image](https://user-images.githubusercontent.com/110108422/206294277-34681551-e08a-4a0d-8f87-480a43494db6.png)

When I sort by updated or by publication date, I get the correct number of records.

When I sort by title, I don't get the speech records (related to #852 )

**Comment by jbukhari** [comment]
Some of this is explained by the fact that when sorting by a field, only records that have that field are returned

**Comment by aaronhelton** [comment]
The reference case here does seem to have been fixed in #905 which is live in QAT now.

@ashley-laura can you tell if this is still an issue, or can we close it as done?

**Comment by ashley-laura** [comment]
@aaronhelton I just replicated the original search Viola did and it is working now, can close as done
