### ISSUE TITLE
Label tabs

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#857]
Currently on the Record Editor tab has a separate label:

![image](https://user-images.githubusercontent.com/110108422/206470919-7bffc026-cce2-4efb-9e59-289edbf68ac7.png)

But it would be good if all items in the main menu would have a corresponding tab label (Bibs, Speeches, Votes, Auths, Browse, Files).

**Comment by aaronhelton** [comment]
This looks pretty easy to do.

**Comment by viola-v** [comment]
Actually, in order to make this useful, we should probably skip MARC Editor at the beginning - if you have many tabs open, that's all you see. Valeria also asked if it's possible to have the tabs in different colors? Basically we need something that makes it easy to see which section is behind the tab (Editor, Bibs, Speeches, Votes, Auths, Browse, Files).

**Comment by aaronhelton** [comment]
I admit I hadn't thought of changing tab colors, and while theoretically possible, this appears to be something that is highly browser dependent. 

We can, however, remove the introductory text on the tab and go directly to the function name.

**Comment by viola-v** [comment]
Yes, let's remove the introductory text and only use what's after the |:
![image](https://github.com/dag-hammarskjold-library/dlx-rest/assets/110108422/89cdc815-0287-41d0-a1c4-be0700004d97)
