### ISSUE TITLE
Sorting speech records by "meeting record" doesn't show results

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#868]
Examples:

![image](https://user-images.githubusercontent.com/110108422/206516335-0238b28b-4fee-42e4-9c55-70f7aa487e26.png)

![image](https://user-images.githubusercontent.com/110108422/206516745-e660f085-3560-408e-ab63-72d57dea3d8d.png)

**Comment by aaronhelton** [comment]
Could be related to #852
