### ISSUE TITLE
998 fields should not be editable

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#871]
They contain legacy data (record creation/last update in Horizon) that we need to preserve and don't want to be changed/deleted by mistake.

**Comment by aaronhelton** [comment]
Set configurations for non-editable fields.

**Comment by viola-v** [comment]
@JoelleSciboz suggested that for the time being we could maybe solve this issue with different views. Most people don't need to see 998, and so we could take it off the default view that everyone has, but add it to specific views (such as ITP). And/or create a specific audit view.

**Comment by JoelleSciboz** [comment]
Add 998 to the hidden fields that can only be viewed when we toggle 'hidden fields.' This field should and will **never** be updated.
<img width="359" alt="hidden fields" src="https://user-images.githubusercontent.com/9261460/221232883-8c0beb68-7774-4649-9d26-dfef48c0f7cc.PNG">

**Comment by Yalshire2004** [comment]
Just for Bib records

**Comment by Yalshire2004** [comment]
Done
