### ISSUE TITLE
Erroneous dates (wrong number of digits) in Horizon got automatically changed when moved to CDB

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#876]
Reported by Valeria:

![image](https://user-images.githubusercontent.com/110108422/206788649-2fd274a2-b296-40f9-b778-861c833cacfd.png)

I think what she's saying is that a record had 9 digits in 269 originally, but when she looked at the record in the MARC Editor, it had already applied the dashes cut off the last digit, resulting in a wrong date.

I haven't tried to replicate this.

**Comment by aaronhelton** [comment]
We're reading the string left to right and applying a pattern to ensure the date is properly formatted (as opposed to "correct"). It may be possible to figure out what someone meant by 019 in a two digit field (01? 19?), but if so it may not be a trivial task.

**Comment by viola-v** [comment]
I didn't mean that we should correct invalid dates automatically, but in the case Valeria described, the date in an existing record was wrong, and then the formatting was applied automatically before she had a chance to fix the date? If I open a record with an invalid date, it should show up in red so that I can correct it as necessary. I thought the dashes got only applied upon save? To replicate that we would need to find existing records with more than 8 digits.

**Comment by aaronhelton** [comment]
This might be a case where cleaning up Horizon data first will prevent an issue from occurring.

**Comment by aaronhelton** [comment]
Also check Hzn->DLX

**Comment by viola-v** [comment]
I think what we need is a report from Horizon for records that have don't have 4, 6 or 8 digits in 269 and not 8 digits in 992, so that we can fix the records that got assigned an incorrect date on export from Horizon.

**Comment by jbukhari** [comment]
@viola-v noted

**Comment by jbukhari** [comment]
Report of invalid dates in 269$a in Horizon

https://unitednations-my.sharepoint.com/:x:/r/personal/bukhari_un_org/Documents/Microsoft%20Teams%20Chat%20Files/269_dl_only.xlsx?d=w2cdd2bf733c14088a4598b57dab75e22&csf=1&web=1&e=ukmKGA

**Comment by viola-v** [comment]
Thank you, @jbukhari! I corrected all records in the report as necessary/appropriate. I'm waiting for feedback from Valeria, but I think then we can close the ticket. With the date validations we shouldn't have any issues with this going forward!

**Comment by viola-v** [comment]
Closing this ticket now!
