### ISSUE TITLE
Diacritics in keyword search

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#877]
Susan: _When I search for names certain diacritics, it does not find the name when searching in the ME.  Vukasinovic works but Vukašinović does not. Same for Barbalic vs Barbalić. , José and Graça both work though.  These are only a few examples, but all diacritics needs to be searchable in names. In Horizon they are ignored when searching._

More examples from Valeria:

    
Some diacritics used in authorities are still not found. Examples: Ørnehaug - Tu’i’onetoa - İstemi̇l
    
Radović

Prvý

l'impunite (French!!!) - trying to find => Association sahrouie contre l’impunité aux camps de Tindouf

**Comment by aaronhelton** [comment]
This is specifically with free text searches, which should be working.
