### ISSUE TITLE
Issue with symbol being converted as part of search

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#879]
Mayumi: _When I search S/Agenda/9180 in the Bibs simple search, it automatically changes it to symbol:S/AGENDA/9180* and nothing shows up because Agenda is spelled not all upper case.  We just have to know to search with single quotation marks but I thought I'd bring it up.  Thank you!_

**Comment by aaronhelton** [comment]
Either don't capitalize automatically or make sure the search is case insensitive.

**Comment by aaronhelton** [comment]
Part of the overall symbol search improvement. (Ticket?)

**Comment by viola-v** [comment]
This has been deployed.
