### ISSUE TITLE
Auths logical fields updates

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#880]
The following logical fields in Auths search need to be added (based on feedback from Griet):

subject
491 $d
591 $a, $b, $c, $d

agenda
491 $d
591 $a, $b, $c, $d

agenda_subject
491 $d
591 $d

agenda_title
591 $c

**Comment by aaronhelton** [comment]
Update logical field configuration and rebuild the logical fields.

**Comment by aaronhelton** [comment]
See: https://github.com/dag-hammarskjold-library/dlx/pull/225

**Comment by aaronhelton** [comment]
The related PR in dlx has been merged, so all that's left here is to update dlx and rebuild the logical fields.

**Comment by jbukhari** [comment]
> The related PR in dlx has been merged, so all that's left here is to update dlx and rebuild the logical fields.

#1131

**Comment by viola-v** [comment]
Adding examples for testing (I couldn't come up with anything meaningful for 591 $a, $b):

subject
491 $d => auth search **subject:"IRAQ--HUMAN RIGHTS"** should retrieve same as **491__d:"IRAQ--HUMAN RIGHTS"**
591 $a, $b, $c, $d
=> auth search **subject:"Administrative and budgetary aspects of the financing of the United Nations peacekeeping operations."** should retrieve same as **591__c:"Administrative and budgetary aspects of the financing of the United Nations peacekeeping operations."**
=> auth search subject:"TIMOR-LESTE SITUATION" should retrieve same as 591__d:"TIMOR-LESTE SITUATION

agenda
491 $d => auth search **agenda:"IRAQ--HUMAN RIGHTS"** should retrieve same as **491__d:"IRAQ--HUMAN RIGHTS"**
591 $a, $b, $c, $d
=> auth search **agenda:"Administrative and budgetary aspects of the financing of the United Nations peacekeeping operations."** should retrieve same as **591__c:"Administrative and budgetary aspects of the financing of the United Nations peacekeeping operations."**
=> auth search agenda:"TIMOR-LESTE SITUATION" should retrieve same as 591__d:"TIMOR-LESTE SITUATION

agenda_subject
491 $d => auth search **agenda_subject:"IRAQ--HUMAN RIGHTS"** should retrieve same as **491__d:"IRAQ--HUMAN RIGHTS"**
591 $d => auth search **agenda_subject:"TIMOR-LESTE SITUATION"** should retrieve same as **591__d:"TIMOR-LESTE SITUATION"**

agenda_title
591 $c => auth search **agenda_title:"Administrative and budgetary aspects of the financing of the United Nations peacekeeping operations."** should retrieve same as **591__c:"Administrative and budgetary aspects of the financing of the United Nations peacekeeping operations."**

@aaronhelton I'm not 100% sure about this, so please let me know if this doesn't work as expected in production (it might be me, not you...)

**Comment by aaronhelton** [comment]
@viola-v  I've tried these searches on dev and don't see the results you indicated above; they don't match between the logical fields and the actual fields. I was hoping we'd be able to find a fix for this today, but since we don't have it, I am going to have to defer this to v2.0.8

**Comment by viola-v** [comment]
This was supposed to be closed by #1131 but the search examples I listed above still don't work as expected, with the exception of the very last one... Reopening!

**Comment by viola-v** [comment]
Re-opening this as none of the sample searches below bring back the desired results:

subject
491 $d => auth search subject:"IRAQ--HUMAN RIGHTS" should retrieve same as 491__d:"IRAQ--HUMAN RIGHTS"
591 $a, $b, $c, $d
=> auth search subject:"Administrative and budgetary aspects of the financing of the United Nations peacekeeping operations." should retrieve same as 591__c:"Administrative and budgetary aspects of the financing of the United Nations peacekeeping operations."
=> auth search subject:"TIMOR-LESTE SITUATION" should retrieve same as 591__d:"TIMOR-LESTE SITUATION

agenda
491 $d => auth search agenda:"IRAQ--HUMAN RIGHTS" should retrieve same as 491__d:"IRAQ--HUMAN RIGHTS"
591 $a, $b, $c, $d
=> auth search agenda:"Administrative and budgetary aspects of the financing of the United Nations peacekeeping operations." should retrieve same as 591__c:"Administrative and budgetary aspects of the financing of the United Nations peacekeeping operations."
=> auth search agenda:"TIMOR-LESTE SITUATION" should retrieve same as 591__d:"TIMOR-LESTE SITUATION

agenda_subject
491 $d => auth search agenda_subject:"IRAQ--HUMAN RIGHTS" should retrieve same as 491__d:"IRAQ--HUMAN RIGHTS"
591 $d => auth search agenda_subject:"TIMOR-LESTE SITUATION" should retrieve same as 591__d:"TIMOR-LESTE SITUATION"

agenda_title
591 $c => auth search agenda_title:"Administrative and budgetary aspects of the financing of the United Nations peacekeeping operations." should retrieve same as 591__c:"Administrative and budgetary aspects of the financing of the United Nations peacekeeping operations."

**Comment by jbukhari** [comment]
@viola-v 

> 491 $d => auth search subject:"IRAQ--HUMAN RIGHTS" should retrieve same as 491__d:"IRAQ--HUMAN RIGHTS"

This should not retrieve the same results. `subject:"IRAQ--HUMAN RIGHTS"` will return more results than `491__d:"IRAQ--HUMAN RIGHTS"` because records with 191$d = IRAQ--HUMAN RIGHTS" will also be in the results when using the `subject` logical field.

One record has 491$d = "IRAQ--HUMAN RIGHTS", while 8 records have 191$d = "IRAQ--HUMAN RIGHTS". Hence  `subject:"IRAQ--HUMAN RIGHTS"` returns 9 results.

**Comment by viola-v** [comment]
Ah, of course, you're right, my wording wasn't precise and I confused myself! Everything is working as intended, so closing this again!
