### ISSUE TITLE
Deleted records appear in results

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#882]
Records that don't exist anymore still appear in results, we discussed that this morning, and Joe is aware that something needs to be done, but I wanted to create a ticket anyway. I think that's also behind #861 

And I think this feedback from Susan is also related: 

I asked Marina to test the merge functionality by merging two authorities, one for Ghazzawi, Q. and one for Ghazzawi, Qasim.  The latter was the surviving authority, and is the only one found when searching by Browse -> Auths -> author.  http://54.87.252.103/uat/records/auths/browse/author?q=ghazzawi&type=auth  When you search in Browse -> Auths -> subject though, the non surving authority still appears.  If you select it, nothing is displayed.  http://54.87.252.103/uat/records/auths/browse/subject?q=ghazzawi&type=auth

**Comment by viola-v** [comment]
This is still an issue - in this case the record had been deleted quite a while back in Horizon:
![image](https://user-images.githubusercontent.com/110108422/220982134-dd636bee-ff84-4228-a02a-93c65bcebe24.png)

These "ghost" records are confusing and might lead to errors...

**Comment by aaronhelton** [comment]
Closed by #1028
