### ISSUE TITLE
Browsing speech records needs option for country_org

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#886]
We need to add the logical field for country_org to the browse options for Speeches:

![image](https://user-images.githubusercontent.com/110108422/207083628-119ed353-55aa-43b5-b594-d64845f1d2d6.png)

**Comment by aaronhelton** [comment]
Also remove related_docs from this list

**Comment by aaronhelton** [comment]
@viola-v and we're removing related_docs from search for this collection?

**Comment by viola-v** [comment]
Yes, it can be removed, speech records don't have this field.
