### ISSUE TITLE
Browsing votes records needs option for related_docs

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#888]
We need to add the logical field for related_docs to the browse options for Votes:

![image](https://user-images.githubusercontent.com/110108422/207084666-126f545e-a3e2-4485-8f3a-a7c0a1a378a3.png)

**Comment by aaronhelton** [comment]
@viola-v does this also need to be in the advanced search?

**Comment by viola-v** [comment]
Yes please!
