### ISSUE TITLE
Issues with adding to basket from more than one page of browse results

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#892]
This was reported by Jessica, she had selected a few items from a browse results page to send to the basket and wanted a few additional items from the next page. But only the items from the next page made it into the basket. I told her that she probably has to click send to basket on the first page first before navigating to the next page, but that doesn't work either. Here's a video showing what happens:

https://user-images.githubusercontent.com/110108422/207370005-40ea228c-e7be-480b-8371-256bd9ac542a.mp4

**Comment by aaronhelton** [comment]
This is closed by #939
