### ISSUE TITLE
Search/browse indexes not updated with latest results (probably only logical fields not working)

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#903]
From Susan: I updated the 110 in the authority for UN Office for Project Service to UNOPS. http://54.87.252.103/uat/editor?records=auths/223671  When I search for UN Office for Project Services in the browse author search, I am not seeing a reference to UNOPS, even though UN Office for Project Services is in the 410 now. http://54.87.252.103/uat/records/auths/browse/author?q=UN%20Office%20for%20Project%20Service&type=auth  When I do it the other way round and search for UNOPS which is now in the 110, I can see that the see reference that is being picked up is the 510 only.  Is this the desired behaviour? http://54.87.252.103/uat/records/auths/browse/author?q=unops&type=auth

I tried it with a record that already had a 410 and it works as intended: http://54.87.252.103/uat/records/auths/browse/author?q=BCPR&type=auth

Here's another example - we have several bib records with the title "work in progress" that were created during the testing period:

![image](https://user-images.githubusercontent.com/110108422/207692607-a05de98e-b4f8-4353-a4ca-6c9bbac3ec7c.png)

But when you do a browse search, they don't show up:

![image](https://user-images.githubusercontent.com/110108422/207692809-0750edda-5b01-4210-8997-fa0000249953.png)

**Comment by jbukhari** [comment]
There are two issues here. One is that the logical field/browse indexes are not deleting old values properly when a record is updated/deleted (known). The other is that a new record created did not get picked up in the search results when searching by title, but it did work seaching by 245.

**Comment by viola-v** [comment]
We already have a ticket for the logical field/browse indexes are not deleting old values properly when a record is updated/deleted #882 

We think that the the issue of a new record not getting picked up in the search results has to do with the fact that Mayumi created them in the old testing environment. We weren't able to replicate the issue in the current UAT environment.

**Comment by viola-v** [comment]
Closing this, should be covered by issue #882
