### ISSUE TITLE
Wrong files attached

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#908]
This record (an old one, created in Horizon) is for a publication but it has three files for official documents attached: ![image](https://user-images.githubusercontent.com/110108422/207697473-b7125d10-9f9c-4fda-a55d-16ed3e69ecdc.png)

Is this just a quirk of the testing database, are files not aligned properly, or would we run into the same issue in production?

The record is correct in the DL (no files attached, just external links): https://digitallibrary.un.org/record/536811?ln=en

**Comment by jbukhari** [comment]
This is from old data in the test DBs with files that wrongly had the symbol "***". That file data has been deleted. @aaronhelton this can be closed
