### ISSUE TITLE
Update validations - Thursday, 15 December

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#912]
**Speeches**

035 should be required

**Auths**

491 subfields a and c should also be valid

**Bibs**

089 subfield b should be added by default when new field is added

Finalized for today

**Comment by aaronhelton** [comment]
Do we have a field definition for speeches 035? It's not in the current validations.

For bibs 089, subfield b is already set as a default subfield. Are there cases where this isn't happening?

**Comment by viola-v** [comment]
For 035, that was my mistake, I thought we had discontinued it, but we still use it in speeches for the ITPP scripts.

I updated the Speeches validation document: 
![image](https://user-images.githubusercontent.com/110108422/208167620-f675ee4d-de2c-4427-a01d-7c301530e207.png)
