### ISSUE TITLE
Remove 998 from all views or solve issue 871

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#915]
@JoelleSciboz suggested that for the time being we could maybe solve this issue in #871 with different views. Most people don't need to see 998, and so we could take it off the default view that everyone has, but add it to specific views (such as ITP). And/or create a specific audit view. Needs a bit further analysis but should then be done before go live to help preserve data integrity.

Possibly related to other tickets concerning views: #862

**Comment by JoelleSciboz** [comment]
We want 998 removed from all viewed to ensure it is not updated. This is a temporary measure. Ideally, we want 998 to be a hidden field like 001, or 008 see issue #871

**Comment by Yalshire2004** [comment]
Done
