### ISSUE TITLE
Default MARC subfields don't show up

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#922]
Did something happen to the validation script?

Examples:

Record originally created from workform:
![image](https://user-images.githubusercontent.com/110108422/208172462-ea62f5da-1b62-4dd7-ab1a-0f943b6ab540.png)

Record cloned:
![image](https://user-images.githubusercontent.com/110108422/208172727-0d9998af-01ff-49b6-a579-89767105bee2.png)

Existing record:
![image](https://user-images.githubusercontent.com/110108422/208172932-0fd45ea4-07c5-4d17-9b77-ec67f1361646.png)

**Comment by aaronhelton** [comment]
Fixed in #924
