### ISSUE TITLE
035 doesn't carry over when cloning record

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#940]
Feedback from Nick, related to speech records: _It seems that tag 035 is a new requirement. So I added it to the record that I’m creating. But when I save it and clone it, the new record clones without  tag 035._

I will test this and update the ticket accordingly.

**Comment by jbukhari** [comment]
035 is supposed to be a field for unique identifiers, which is why it is excluced on clone. Probably, we want to make this field non required.

**Comment by viola-v** [comment]
In speech records, 035 should be a **required** field, it is **not** unique (all current speech records have the value Q1000000), and it is used for the extraction of speeches in the ITP app. It also needs to be included when cloning speech records. We don't use 035 for any records currently, so it can be included when cloning all records if that is easier to implement; we just have to remember to remove it from other bib records like we currently do if the field is present. (But since it was always assigned manually, we cannot guarantee unique values anyway.)

**Comment by jbukhari** [comment]
OK we can remove 035 as excluded during clone. But just to note, this is not the right use of 035. 035 is supposed to be a system control number, and in fact DL uses it this way. On export to DL, we have to alter this field to ensure 035$a is a unique identifier (out bib/auth#). 

Surely there is a better way to designate a record as a speech, without this obscure code?

@grozdanic  Does the new ITP process require that 035$a is set to "Q1000000"?

**Comment by grozdanic** [comment]
@jbukhari Yes, for the time that is how ITS/Speeches are filtered out .. if 'Q' exists in 035__a

**Comment by viola-v** [comment]
Apparently 035 is the only field that is consistently used to identify the speech records. From Valeria: _All speech records carry that field, whereas the practice to include 930 ITS, started around 2003 (GA, 58th session). I don't also think that B22 is a good option._

Something to look at again during the information architecture review...

**Comment by jbukhari** [comment]
For the future, there needs to be a better criteria for than 035$a contains "Q", or 089$b equals "B22"
