### ISSUE TITLE
"Locked" icon in search results shouldn't be clickable 

### ISSUE THREAD

**Issue by jbukhari** [dag-hammarskjold-library/dlx-rest#941]
The lock icon has become clickable but it shouldn't be

**Comment by aaronhelton** [comment]
The lock icon was clickable for a while, because we had intended that someone could override the lock if they needed to. However, I don't see this function working.

**Comment by jbukhari** [comment]
When clicking the lock icon, it changes to a spinner icon but does nothing. This was not the case before.
