### ISSUE TITLE
905 save action for older authorities

### ISSUE THREAD

**Issue by susanhussein** [dag-hammarskjold-library/dlx-rest#981]
For older existing authorities that are being edited, a 905 field to indicate the local field should be generated when saving changes. This would be DHL for any authorities in NY, GEN from Geneva.

https://www.un.org/depts/dhl/unbisref_manual/name/n905.htm

**Comment by aaronhelton** [comment]
Let's schedule a meeting to understand what's required.

**Comment by viola-v** [comment]
Some ideas:

- Add two buttons to the authority record menu, one for 040 and one for 905 with the default values for NY. We’d still have to add 915 manually (unless we wanted to add another button for that as well, but it would only be used for personal names)

- For authorities created from the bib record, when 040 is NNUN add 905 DHL, and if the authority in the bib record is 700, add 915__a:PN.

- Use the save logic similar to 981/989 to add 040 and/or 905 based on existing fields – if 040 is NNUN, add 905 DHL and vice versa. If the authority record has a 100 field, add 915__a:PN.

**Comment by viola-v** [comment]
Just to record that 905 is currently used by the ITPP scripts...

**Comment by viola-v** [comment]
Discussed at today's UX meeting and decided to automatically add 905__a:DHL to all records that don't already have a 905 field upon save. The authority records concerned are mostly based on speech records, so they would have been created by NY, and thus 905__a:DHL will be the correct library anyway. To be confirmed by Susan...

**Comment by viola-v** [comment]
This works fine, except that if the record has an existing 905 field with a different value (GEN for Geneva records), it gets overwritten with the DHL value. That shouldn't happen. If the record already has a 905 field, regardless of the value, it should not be overwritten.
