### ISSUE TITLE
Indexes don't update quickly enough

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#986]
Susan H. merged two authorities yesterday, and when she searched for the variant record in the 400 field, she got a result in Browse -> Auths -> subject search, but not in Browse -> Auths -> author. I checked today, and now we get results in both indexes. These indexes need to update pretty much immediately, otherwise we risk making mistakes.

**Comment by viola-v** [comment]
Apparently also regular updates to authority records (such as adding diacritics to a name) take at least a few minutes to manifest. Valeria flagged this example:

![image](https://user-images.githubusercontent.com/110108422/224110271-5106bb05-b6f0-42b0-8c43-99a5c4fdd717.png)

**Comment by aaronhelton** [comment]
Closed by #1028
