### ISSUE TITLE
Cursor moves to beginning of field after copy and paste

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#991]
When I copy and paste text into a field, the cursor moves to the beginning of the field afterwards instead of just staying in place.

https://user-images.githubusercontent.com/110108422/220405556-25e34efa-90c1-42ec-915d-c0a680440cc8.mp4

**Comment by viola-v** [comment]
Susan is pretty sure that this is a new bug and wasn't the case earlier. @jbukhari Is it possible that it got introduced when the paste feature for the authority lookup (#904 ) was fixed?

**Comment by aaronhelton** [comment]
This will have to be done in the record refactor.

**Comment by jbukhari** [comment]
@aaronhelton I believe this is referring to pasting from the system clipboard, not field copy+paste

@viola-v @susanhussein There is a pending fix for this. Note that you always jump to the beginning or end of a text field with ctrl-a and ctrl-e

**Comment by aaronhelton** [comment]
@jbukhari yes, correct, copy+paste from system clipboard. Just note also that this will have to be re-done or checked again during record refactor.
