### ISSUE TITLE
Cannot create new authority from within bib record

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#993]
https://user-images.githubusercontent.com/110108422/220645688-69509ee1-cc6a-418f-b114-a1001a366f99.mp4

**Comment by viola-v** [comment]
This does work in UAT!

**Comment by grozdanic** [comment]
I was able to do it in PROD. The trick may be to wait for the search to finish before clicking on the plus link to create new authority

**Comment by viola-v** [comment]
It's working now - Joe had forgotten to run one of the admin scripts after refreshing the data. Closing!
